### ISSUE TITLE
Prioritize tmp dirs

### ISSUE THREAD

**Issue by ericaltendorf** [ericaltendorf/plotman#11]
Currently plotman grabs the first tmp dir that is ready.

This means if the global stagger setting is the limitation (rather than disk phase readiness), jobs will bunch up on the earliest disks.  We should schedule jobs to the disks that are in the *best* state to take a job (similar to how we prioritize archiving from dst dirs)

**Comment by BasilHorowt** [comment]
Looks like the linked pr solves this
