### ISSUE TITLE
Return ERR in interactive.py

### ISSUE THREAD

**Issue by iliaorkin** [ericaltendorf/plotman#124]
Hello,

I did a fresh install last night of chia and Plotman development, and am running into the error below when running plotman interactive:
![image](https://user-images.githubusercontent.com/9367687/115125808-9941be00-9f98-11eb-921f-10be4e1c4316.png)

Any ideas on what the issue might be? It seemed to have been running fine last night before I reinstalled Ubuntu 20.04

Thanks!

**Comment by iliaorkin** [comment]
The plotting loop actually starts without any issues if i run "plotman plot", I just can't get the interactive to work

**Comment by altendky** [comment]
Looks like https://github.com/ericaltendorf/plotman/issues/64.

> current workaround: try increasing your terminal size...

Obviously not a great solution but we haven't gotten to this yet.  Sorry for the trouble.

**Comment by iliaorkin** [comment]
Thank you very much! That fixex it!
