### ISSUE TITLE
Not able to start Plotman

### ISSUE THREAD

**Issue by William8Work** [ericaltendorf/plotman#136]
I followed the instruction to install. After that, when trying to start Plotman by:

$ ./plotman.py
```

Traceback (most recent call last):
  File "./plotman.py", line 17, in <module>
    from job import Job
  File "/home/chia/plotman/job.py", line 15, in <module>
    import psutil      # apt-get install python-psutil
ModuleNotFoundError: No module named 'psutil'
```

however, if I start python, and within python, `import psutil `is totally ok.

what should I do?

**Comment by ericaltendorf** [comment]
Look for the new install instructions, to be announced imminently....

**Comment by altendky** [comment]
@William8Work sorry for the trouble.  We recently reworked the plotman setup process.  See https://github.com/ericaltendorf/plotman#installation and let us know if that gets you started.  You won't need the git clone anymore.

**Comment by William8Work** [comment]
yes I was able to follow that and start plotman. thank you!
