### ISSUE TITLE
Error when starting Plotman: ModuleNotFoundError: No module named 'readline'

### ISSUE THREAD

**Issue by gzl333** [ericaltendorf/plotman#157]
Hi, thanks for developing this great tool. I'm excited about it.
But after installation I met this error:

`(venv) [root@centos8 chia-blockchain]# plotman version
Traceback (most recent call last):
  File "/root/Downloads/chia-blockchain/venv/bin/plotman", line 5, in <module>
    from plotman.plotman import main
  File "/root/Downloads/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 10, in <module>
    from plotman import analyzer, archive, configuration, interactive, manager, plot_util, reporting
  File "/root/Downloads/chia-blockchain/venv/lib/python3.7/site-packages/plotman/archive.py", line 14, in <module>
    from plotman import manager, plot_util
  File "/root/Downloads/chia-blockchain/venv/lib/python3.7/site-packages/plotman/manager.py", line 6, in <module>
    import readline  # For nice CLI
ModuleNotFoundError: No module named 'readline'`

I'm using CentOS Stream release 8 and python 3.7.7
Is there anything I'm doing wrong? How can I fix this?
Thanks a lot!

**Comment by altendky** [comment]
`readline` is [in the Python stdlib](https://docs.python.org/3/library/readline.html).  I don't know my way around CentOS, but I know Debian breaks the stdlib up into multiple system packages.  Perhaps CentOS has done this as well?  I'll follow up here if I have a chance to dig into that myself.

**Comment by altendky** [comment]
Was there such a system package to install?  I would be interested to know in case this comes up again.  Thanks.

**Comment by gzl333** [comment]
Hi, it turns out to be the errors during compiling and installing python 3.7.3 on CentOS8. The install process lost readline package and curses package somehow. 
A simple reinstall would solve the problem.
Thanks again for your great work!
