### ISSUE TITLE
source code invalid path issue when developing in Windows

### ISSUE THREAD

**Issue by DeXtmL** [ericaltendorf/plotman#160]
under "plotman/_test/resources", it contains two log files:
**2021-04-04-19:00:47.log
2021-04-04-19:00:47.notes**

These 2 files use path character ":" in their file names, which is not valid for Windows path name. This makes Git complaining about the path incorrectness all the time.

Please change the file name, replacing ":" by "-" or "_"

**Comment by altendky** [comment]
This is being discussed over in https://github.com/ericaltendorf/plotman/issues/144.  The annoying bit is an apparent lack of a standard date and time format that is actually filesystem compatible across platforms.  But, we'll pick something.
