### ISSUE TITLE
Plotman "stop" command?

### ISSUE THREAD

**Issue by mc19000** [ericaltendorf/plotman#177]
Plotman plot starts the process.

Is there a command to completely stop the process and stop new plots from being created?

Thanks

**Comment by dicoolx** [comment]
ctrl + c

**Comment by ericaltendorf** [comment]
Plotman only spawns new plot jobs while it's running, so to stop the
spawning of new jobs, you can stop plotman.

If you're in 'interactive' mode, you can also keep the monitor running but
not spawn new plots by pressing the <p> key (it toggles plotting)

**Comment by altendky** [comment]
My imagination is that `plotman plot` would end up being used as a service and you would `systemctl start plotman` and `systemctl stop plotman` etc.  You could enable it to start on boot.  When it crashed it would be restarted.  I presume that would handle log rolling of our output, etc.  I don't know a specific reason you couldn't set this up now, but I also haven't actually done it or heard of anyone doing it.  This would be significantly more useful with a monitoring version of interactive mode.  Or at least a `plotman interactive --monitor` cli option.

**Comment by BasilHorowt** [comment]
I'm going to close this because `q` exists.  @ericaltendorf your notes about using plotman as a service seem good so created a new issue to capture them here: https://github.com/ericaltendorf/plotman/issues/285

I thought about renaming this issue but it seemed too distant from the original report.
