### ISSUE TITLE
Please explain archival configuration

### ISSUE THREAD

**Issue by jeremyj** [ericaltendorf/plotman#178]
Hi,

On my farmer I have multiple hard drives mounted as /media/disk1, /media/disk2, /media/diskN all configured as plot destination dirs.
I do not understand how to configure plotman to use all (any) of the dirs and how the indexing works. For example: how can I specify more than one module/path in the archive section of the configuration? How to I use indexes to avoid contention?

Thanks

**Comment by drygb** [comment]
You should use "/media/" as path for archive - it should autodetect all disks within the directory.

**Comment by altendky** [comment]
If you mount other things in `/media` then you'll want to separate things.  I had to add a directory to isolate my final plot holder mount points.

For indexing you can just set a different index on each system that is archiving.  0 on the first, 1 on the second, etc.

**Comment by mjsr** [comment]
@jeremyj have you tried the Archiving wiki page? I completed it not long ago since I was feeling a bit confused.

Here's the link: https://github.com/ericaltendorf/plotman/wiki/Archiving

**Comment by jeremyj** [comment]
@mjsr thank you for pointing that out!
I wasn't aware there was a wiki.

**Comment by mjsr** [comment]
Precisely why I have made this PR: https://github.com/ericaltendorf/plotman/pull/241 :)

**Comment by ericaltendorf** [comment]
You are rightly excused :)  The wiki didn't exist until a couple days ago.
