### ISSUE TITLE
No plot ID or phase info

### ISSUE THREAD

**Issue by farmerscott** [ericaltendorf/plotman#179]
I just started using plotman yesterday and really the only issue I'm having thus far is that I am not seeing any plot IDs or phase details?  Not sure if I managed to misconfigure something or what?

**Comment by farmerscott** [comment]
Nevermind, I figured it out.  Looks like my pointing the logs parameter to a sym link was mucking up the works.  I changed this to the full path and everything looks great now.

**Comment by altendky** [comment]
At first thought, we should be able to process symlinks.  We're probably just not doing the comparison right.  It's not the simplest thing to get right and I can't remember exactly where it was I last dealt with this...  hmm.
