### ISSUE TITLE
No eligible tempdirs...

### ISSUE THREAD

**Issue by farmerscott** [ericaltendorf/plotman#180]
Now for the next hurdle...  I was able to I thought get plotman working great.  However, now I'm running into the error of "no eligible tempdirs".  I'm running on a 2TB NVMe tempdir with only a single plot going in it.  I actually changed "tmpdir_max_jobs: 4" so I'm really not sure what's going on here.

**Comment by cbacon93** [comment]
Hi, just to clarify were you not able to run plots at all?

**Comment by cbacon93** [comment]
Hi, check those parameters;

```
tmpdir_stagger_phase_major: 2
tmpdir_stagger_phase_minor: 1
# Optional: default is 1
tmpdir_stagger_phase_limit: 1
```

By default, plotman only allows one plot to run below phase 2:1

**Comment by farmerscott** [comment]
Thanks for the help.  This was definitely my issue and I MUCH better understand the staggering and limits now.
