### ISSUE TITLE
job_buffer variable is not followed

### ISSUE THREAD

**Issue by mist0706** [ericaltendorf/plotman#183]
Changed the job buffer value from the default 4000 to 3400. Yet the process still uses 4000MB of memory.

**Comment by ericaltendorf** [comment]
On already running jobs, or on newly started jobs?

**Comment by mist0706** [comment]
Newly started jobs as well
![image](https://user-images.githubusercontent.com/10143260/116438959-4943e080-a84f-11eb-893b-95371ba4c6f4.png)

**Comment by ericaltendorf** [comment]
that's used memory.  the memory a process uses is the sort buffer memory
plus everything else the process is doing.  this is just chia behavior,
doesn't relate to plotman.  plotman is (as you can see) issuing the plot
invocations with the correct `-b 3400`.

**Comment by mist0706** [comment]
Aha that makes sense. Does plotman take ram into consideration when starting new plots?

**Comment by altendky** [comment]
Nope.  The closest you come is the global max which you could choose based on total ram and ram generally used per process.
