### ISSUE TITLE
Plotman for MacOS Bigsur

### ISSUE THREAD

**Issue by erdincsk** [ericaltendorf/plotman#189]
I'm wondering if plotman runs on mac bigsur 11.3?

I have installed plotman and plot config. when i start plotman, it creates a job but not the temp files in defined temp directories. It just creates log and logs with its loop but nothing happends on temp directories.

> .starting plot loop
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:47:08.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:47:28.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:47:48.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:48:08.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:48:28.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:48:48.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:49:08.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:49:28.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:49:48.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:50:08.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:50:29.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:50:49.log')
...sleeping 20 s: (True, 'Starting plot job: chia plots create -k 32 -r 2 -u 128 -b 4608 -t /Volumes/ssd_1tb/tmp -d /Volumes/2tb_hdd/plot ; logging to /Users/erdinckeloglu/Documents/chiaplot/logs/2021-04-29-11:51:09.log')

here is one example log file,

> 2021-04-29T11:12:43.957  chia.plotting.create_plots       : [32mINFO    [0m Starting plot 1/1[0m
Starting plotting progress into temporary dirs: /Volumes/ssd_1tb/tmp and /Volumes/ssd_1tb/tmp
ID: 433cd12c71fbe03e1f097b1f636ab1490ed81e7b1dac298c7d56d954b3a36a4f
Plot size is: 32
Buffer size is: 4608MiB
Using 128 buckets
Using 2 threads of stripe size 65536
Starting phase 1/4: Forward Propagation into tmp files... Thu Apr 29 11:12:54 2021
Computing table 1

**Comment by altendky** [comment]
There have been some issues with process detection on macOS.  Maybe try the development branch where there have been a few fixes.  You can install it by following the regular installation instructions in the readme but substituting `@development` where they say `@main`.

Sorry for the trouble.

**Comment by erdincsk** [comment]
i will check let you know if it works. thanks!

**Comment by kareemlukitomo** [comment]
<details><summary>Big Sur</summary><p>

![image](https://user-images.githubusercontent.com/16204162/116585332-7ae9a400-a942-11eb-88a3-a2b24837ca4f.png)

</p></details>

Just wanted to let you know Plotman is working on my Hackintosh Big Sur 11.2.3

I just followed instruction in the README and also installing it with https://github.com/Chia-Network/chia-blockchain/wiki/INSTALL#MacOS hope it helps! @erdincsk

**Comment by erdincsk** [comment]
> There have been some issues with process detection on macOS. Maybe try the development branch where there have been a few fixes. You can install it by following the regular installation instructions in the readme but substituting `@development` where they say `@main`.
> 
> Sorry for the trouble.

Hello again,

i tried with dev version and everything works seem fine now.

Thanks :)

**Comment by tim-brand** [comment]
I also want to confirm that the dev version is working on mac.
