### ISSUE TITLE
More plots in phase 1 than defined

### ISSUE THREAD

**Issue by MichaGithubel** [ericaltendorf/plotman#191]
Why do i have 5 plots in phase 1? 

2 at 1:2 (SSD1)
1 at 1:4 (SSD2)
1 at 1:5 (SSD3) 
1 at 1:7 (SSD4)

If my config is this:

tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

Shouldn't i have a maximum of 4 plots in phase 1? 1 Plot on each SSD?
It feels like SSD1 started the phase 1 in duplicate as mistake, both have same wall and dst folder. tmp size is +-1G and ID is different, too.

Is this a bug or am i missing something?

**Comment by altendky** [comment]
Any chance there were any combination of multiple instances of `plotman interactive` and `plotman plot` running at the same time?

**Comment by MichaGithubel** [comment]
> Any chance there were any combination of multiple instances of `plotman interactive` and `plotman plot` running at the same time?

1 instance of "plotman plot" in one terminal window and
1 instance of "plotman interactive" in another terminal window

This problem only happened once so far

**Comment by ericaltendorf** [comment]
the tmpdir_* parameters apply per temp-dir, rather than globally.  they're
intended to control IO per temp dir, to avoid too many jobs getting bunched
up on one drive.

if you want to stagger things globally, use the global stagger setting (in
minutes)

**Comment by altendky** [comment]
@MichaGithubel, this is a common and understandable misconception about how to use plotman.  The interactive mode and plot mode both will launch plots.  Interactive is not purely a monitor.  Usually, running both won't have any odd effects but technically it does stand a chance of doing it.  This has come up a few times now.  I have some interest in changing things up a bit such that there is more separation from the monitoring/dashboard and the underlying plot-running service but that hasn't bubbled up to the top of the priority list yet.

**Comment by ericaltendorf** [comment]
Agreed, this is not documented and not obvious.  Apologies for that, we
will try to make things better.
