### ISSUE TITLE
plots stay in stat SLP

### ISSUE THREAD

**Issue by drewmullen** [ericaltendorf/plotman#199]
howdy - sorry for multiple issues in one day... once i have my arms wrapped around this thing id love to help contribute. this seems like a _fantastic_ project!
```
$ plotman status
 plot id    k           tmp            dst   wall   phase    tmp    pid   stat    mem   user    sys   io
d100ec50   32   /chia-plot1   /chia-buffer   1:14     1:5   175G   2551    SLP   4.9G   1:39   0:03   2s
dafd1a46   32   /chia-plot0   /chia-buffer   1:44     1:7   173G   1987    SLP   4.7G   2:25   0:05   2s
```
^ been this way for hours

```
$ cat ~/.config/plotman/plotman.yaml | egrep -v "^\s*(#|$)"
user_interface:
        use_stty_size: True
directories:
        log: /home/farmer3/chia/logs
        tmp:
                - /chia-plot0
                - /chia-plot1
        dst:
                - /chia-buffer
        archive:
                rsyncd_module: plots
                rsyncd_path: /mnt/synology/usbshare1/rsynctest
                rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
                rsyncd_host: 192.168.2.101
                rsyncd_user: farmer3
scheduling:
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        tmpdir_stagger_phase_limit: 1
        tmpdir_max_jobs: 3
        global_max_jobs: 10
        global_stagger_m: 30
        polling_time_s: 20
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 3         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 4000     # Per job memory
```

these drives work _fine_ with `chia plots create -k 32 -n 4 -b 4000 -r 4  -t /chia-plot0 -d /chia-buffer`

Fedora 34
python 3.7.7

**Comment by altendky** [comment]
The `wall` time reported is less than two hours.  The same two plots (`d100` and `dafd`) have been sitting there for several hours reporting the same `wall` times etc?

**Comment by drewmullen** [comment]
you're correct, those `wall` times are like accurate and i was rounding 1:45 up to 2 (guilty). phase 1 usually takes ~ 1 hr on this machine so I'm comparing to normal performance. The way its configured i would have expected several plots by now? 
When I wasn't seeing progress (when i made this post) I kicked one off manually (`chia plots create...`) to validate that things were "working" with chia but now im afraid that the manual job has killed plotman lol

```
$ plotman status
 plot id    k           tmp             dst   wall   phase    tmp    pid   stat    mem   user    sys     io
--------   32   /chia-plot0   /chia-buffer/   2:09     ?:?      0   3395    RUN   1.9G   3:17   0:07   0:03
d100ec50   32   /chia-plot1    /chia-buffer   3:30     3:2   206G   2551    RUN   4.7G   3:56   0:09   0:10
dafd1a46   32   /chia-plot0    /chia-buffer   4:00     3:4   166G   1987    RUN   4.7G   4:22   0:10   0:14
```

```
$ plotman plot
Traceback (most recent call last):
  File "/home/farmer3/chia-blockchain/venv/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/farmer3/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 143, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/home/farmer3/chia-blockchain/venv/lib/python3.7/site-packages/plotman/manager.py", line 82, in maybe_start_new_plot
    tmp_to_all_phases = [(d, job.job_phases_for_tmpdir(d, jobs)) for d in dir_cfg.tmp]
  File "/home/farmer3/chia-blockchain/venv/lib/python3.7/site-packages/plotman/manager.py", line 82, in <listcomp>
    tmp_to_all_phases = [(d, job.job_phases_for_tmpdir(d, jobs)) for d in dir_cfg.tmp]
  File "/home/farmer3/chia-blockchain/venv/lib/python3.7/site-packages/plotman/job.py", line 21, in job_phases_for_tmpdir
    return sorted([j.progress() for j in all_jobs if j.tmpdir == d])
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

most likely i owe you another test where i wait for all these to finish then kill them off and start plot man over and just _wait_. after about 30m past normal phase 1 timings, i got nervous, kicked off a manual job and i suspect that may have borked it

**Comment by drewmullen** [comment]
if i was to run manual jobs, how can i do that without confusing plotman? `chia plots create ... | tee ~/<log_location>/<something?>`

**Comment by altendky** [comment]
There are several fixes in the development branch which can be installed by using `@development` instead of `@main` in the instructions.  Though, it still isn't the best at jobs that you don't carefully start in the expected way.

Plots will take longer when you have multiple going than when you only have one.  Exactly how much depends on your whole system.  But, plotman just runs commands like you would.  In fact, it literally gives a command line to bash just as you probably do.  I want to change it to not use bash, but for now it does.  So, once the plotting is started, plotman has basically no effect on that job.  You can see the command lines either in the `plotman interactve` log or via `ps aux | grep 'chia plots create'` or similar.

If you are concerned about the performance of your plotting hardware I would suggest seeing what help you can get in `#plotting-hardware` on the Chia keybase.

But, your configuration you posted is going to limit to one job in phase 1 due to `tmpdir_stagger_phase_limit: 1` and the two parameters above it.  Even after that you've got a tmp dir max of 3.  Also, you have a stagger of 30 minutes which seemed to have been the limiting configuration when the second listed job was started.

**Comment by ericaltendorf** [comment]
And, regarding process state sleep, I beleive that's expected; processes in
phase one spend a lot of time in sleep.  I haven't figured out why, but
afaict it has to do with the plotter and the Linux kernel, not plotman.

**Comment by drewmullen** [comment]
this is user error / confusion on the status which lead to random errors that should not happen. perhaps the statuses can be defined in docs and provide some context to avoid future confusion?

also should have a better error message when plots are found but not manageable by `plotman`. example:

```
$ plotman status
 plot id    k            tmp             dst    wall   phase   tmp    pid   stat    mem    user    sys     io
--------   32   /chia-plot0/   /chia-buffer/    7:48     ?:?     0   6506    RUN   1.7G    9:11   0:23   0:43
```

```
$ plotman {plot, interactive}
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

**Comment by ericaltendorf** [comment]
Plotman is just reporting the linux process state via psutil.  We should
probably make that clearer.  Beyond that, I would put it on the user to
read about and learn if they want to use that information.  We have so much
documentation to write on basic aspects of plotman before we'd get to
general Linux information.  We're just a couple of volunteers trying to
improve plotman in our spare time between our day jobs.

Agreed we need better support for plots started not by plotman.  I thought
we'd made progress on that.  If you don't mind, could you:
1) file a separate issue to improve documentation of status columns
2) try latest code from development branch and see if it still doesn't
detect other plot jobs; if so, file an issue describing that
3) then we can close this issue

thanks,
eric

**Comment by altendky** [comment]
I've fixed one or two cases of the `>` failure.  Would have to check which were merged to development.  Of course, there might be more.  Whenever we get to adding type hints, that'll help highlight cases like this.

**Comment by drewmullen** [comment]
https://github.com/ericaltendorf/plotman/issues/217
https://github.com/ericaltendorf/plotman/issues/215

tyvm
