### ISSUE TITLE
Virtually every input I try gives me this error

### ISSUE THREAD

**Issue by th3gamingfreaks** [ericaltendorf/plotman#201]
Sorry I couldn’t get a proper screenshot but I don’t know how to get a ss from my linux machine been trying to get plotman setup for a few hours now, if someone could show me an example yaml config it would be helpful but in getting this error saying scanner error after pretty much every plotman command I input 
![image](https://user-images.githubusercontent.com/46638370/116768418-6c63c100-aa04-11eb-8260-559aac3dd171.jpg)

**Comment by altendky** [comment]
https://github.com/ericaltendorf/plotman/blob/5788e7fa2df2186ccb94db2d388766f9d52116a4/src/plotman/resources/plotman.yaml

You seem to have a sequence (each entry starts with a leading `-`) where one is not expected.  That is on line 27 at column 15.  If you paste your configuration file here we can probably point out the issue.

**Comment by th3gamingfreaks** [comment]
i tried my best but i couldnt seem to figure exactly how it wanted me to format my directory links was i supposed to put it after the 
[plotman.txt](https://github.com/ericaltendorf/plotman/files/6409714/plotman.txt)

**Comment by th3gamingfreaks** [comment]
``# Default/example plotman.yaml configuration file

# Options for display and rendering
user_interface:
        # Call out to the `stty` program to determine terminal size, instead of
        # relying on what is reported by the curses library.   In some cases,
        # the curses library fails to update on SIGWINCH signals.  If the
        # `plotman interactive` curses interface does not properly adjust when
        # you resize the terminal window, you can try setting this to True. 
        use_stty_size: True

# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: /home/chia/chia/logs

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp: /media/gamer/plotting  
                - /mnt/tmp/00
                


        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                "/mnt/tmp/00":
                        tmpdir_max_jobs: 6

        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a

        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        dst: /media/gamer/easystore
                - /mnt/dst/00
                - /mnt/dst/01

        # Archival configuration.  Optional; if you do not wish to run the
        # archiving operation, comment this section out.
        #
        # Currently archival depends on an rsync daemon running on the remote
        # host, and that the module is configured to match the local path.
        # See code for details.
        archive:
                rsyncd_module: plots
                rsyncd_path: /plots
                rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
                rsyncd_host: myfarmer
                rsyncd_user: chia
                # Optional index.  If omitted or set to 0, plotman will archive
                # to the first archive dir with free space.  If specified,
                # plotman will skip forward up to 'index' drives (if they exist).
                # This can be useful to reduce io contention on a drive on the
                # archive host if you have multiple plotters (simultaneous io
                # can still happen at the time a drive fills up.)  E.g., if you
                # have four plotters, you could set this to 0, 1, 2, and 3, on
                # the 4 machines, or 0, 1, 0, 1.
                #   index: 0


# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before tmpdir_stagger_phase_major tmpdir_stagger_phase_minor
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major, phase minor]
        tmpdir_stagger_phase_major: 3
        tmpdir_stagger_phase_minor: 3
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 3

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 6

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 8

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 30

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20


# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 2         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3800     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        #   farmer_pk: ...
        #   pool_pk: ...

**Comment by altendky** [comment]
Maybe something like this, if you actually want all those drives used.

```yaml
        tmp:
                - /media/gamer/plotting  
                - /mnt/tmp/00
```
```yaml
        dst:
                - /media/gamer/easystore
                - /mnt/dst/00
                - /mnt/dst/01
```

**Comment by BasilHorowt** [comment]
@th3gamingfreaks did you have luck after correcting the invalid yaml? Going to close this issue as anything that is "ScannerError" indicates the config couldn't be parsed
