### ISSUE TITLE
Plotman vs Harvestor

### ISSUE THREAD

**Issue by teamhzipfs** [ericaltendorf/plotman#202]
Hi I wonder if anyone has tested figures which compare the Plotman vs Chia Harvestors? In general which one is faster on a cluster basis?

Many thanks!

Cheers,
Chao

**Comment by altendky** [comment]
They do unrelated things as far as I know.  plotman just schedules execution of `chia plots create` for you.  A harvester handles the completed plots to find proofs.  At least roughly.

**Comment by teamhzipfs** [comment]
Thanks for the reply.
AFAIK, the plotman program schedules different plots based on different HDDs mounted as different directories, which means it can be used to build a cluster if I mount network HDDs as local directories. So my question is: performance wise, how does it compares to using Harvestors on these network HDDs (all connected to a Chia full node) in a cluster? I.e. mounting network HDDs and use Plotman for scheduling vs using Harvestors to build clusters?

Cheers!
Chao

**Comment by ericaltendorf** [comment]
This sounds like a question about setting up a chia operation, not really
an issue with plotman software.

General discussion topics like this would be better on one of the
discussion forums.

**Comment by teamhzipfs** [comment]
ok thanks - after some thinking over I think I got the idea. Many thanks any way.
