### ISSUE TITLE
plotman plot running, but I cannot find it

### ISSUE THREAD

**Issue by teaouu** [ericaltendorf/plotman#206]
I cannot reboot my computer because it is remote and I need to stop plotman. Might have limited knowledge, but I cannot find my plotman plot process with ps -ef. Is it somewhere else?

**Comment by ericaltendorf** [comment]
Sorry, this channel is intended for reporting issues or bugs in the plotman
software.  We aren't well equipped to provide consulting on
running plotman.  Please try the keybase channels.
