### ISSUE TITLE
documentation: explanation / context of the "STAT" column in plotman status

### ISSUE THREAD

**Issue by drewmullen** [ericaltendorf/plotman#217]
some explanation / context around the plotting statuses would be helpful and likely prevent further issues from being filed:

```
$ plotman status
 plot id    k           tmp            dst   wall   phase    tmp    pid   stat    mem   user    sys   io
d100ec50   32   /chia-plot1   /chia-buffer   1:14     1:5   175G   2551    SLP   4.9G   1:39   0:03   2s
dafd1a46   32   /chia-plot0   /chia-buffer   1:44     1:7   173G   1987    SLP   4.7G   2:25   0:05   2s
```

reference: https://github.com/ericaltendorf/plotman/issues/199#issuecomment-830617370

**Comment by piotrkochan** [comment]
```
        if status == psutil.STATUS_RUNNING:
            return 'RUN'
        elif status == psutil.STATUS_SLEEPING:
            return 'SLP'
        elif status == psutil.STATUS_DISK_SLEEP:
            return 'DSK'
        elif status == psutil.STATUS_STOPPED:
            return 'STP'
        else:
            return self.proc.status()
```

**Comment by Monstarules** [comment]
@piotrkochan commenting with code from this repository isn't the answer to this question. There's more to it than that. The actual question was in regards to what the different statuses mean, and how to make them clearer, as mentioned in #199 . After reading the documentation of psutil, Chia, Plotman, and Linux status codes, I'm going to attempt to take a stab at possibly providing some insight:

**RUN**
The process is currently running, meaning that it is reading and or writing data to the disk. Self explanatory.

**SLEEP**
The process itself is asleep, as it is not reading or writing data to the disk. Chia in general will call several other processes when making a plot. It is not uncommon for a few processes to be in a standby mode, especially the actual "plot" process, of which the status we see in Plotman. Status SLP does not mean that your plotting has stopped.

**DSK**
The disk itself is asleep and not running. Most disks will power themselves down by default, unless they are special kind of disk like the ones used in servers (Enterprise types). This can be rectified for normal disks by making edits to disk power options, I believe that it is under a utility known as "hdparm", where you edit the amount of time it takes between no read/write and disk sleep. Unlike the SLP status, this one typically does mean that you are not plotting anything.

**STP**
The process is stopped. You are not plotting at all. This one is pretty self explanatory.

**Comment by Monstarules** [comment]
Now, using that basic info, let's expand a bit: if your plots seem to be stuck on **SLP** it may have to do with improper or nonexistent staggering. It is best to stagger your plots, else multiple plots might be trying to access the same resources at the same time, which bogs down the disk (especially if you're trying to read and write to the same one), and may make your plots appear to be in a **SLP** status for a long time.

**Comment by Fmstrat** [comment]
@Monstarules is there any additional info you can give on `SLP`?

I have three plots on three disks running (1 per disk) on a more than capable CPU with 64GB of RAM:
```
  #    plot id    k             tmp   dst   wall   phase    tmp      pid   stat    mem   user    sys     io                                 
  0   5ac4f255   32   data/tmp/plot     .   1:44     1:7   180G   482966    SLP   5.3G   2:53   0:07     2s                                 
  1   3aed4dec   32        mnt/sdb1     .   2:27     2:1   197G   461155    RUN   1.7G   3:28   0:09   0:04                                 
  2   7ec29aed   32        mnt/sda1     .   2:57     2:4   209G   455588    RUN   1.5G   3:47   0:10   0:07  
```
However the first plot has been in SLP for a long time. What would I do to debug this?

**Comment by Fmstrat** [comment]
As I read into this more, there seems to be some confusion around what `STATUS_SLEEPING` truly means in `psutil`. For instance, look here: https://gist.github.com/larytet/3ca9f9a32b1dc089a24cb7011455141f#file-job-py-L23

In this case, they assume an application is running even when it is in WAIT or SLEEP status. I've also noticed that my log file for the `SLP` plot is continuing to receive entries even when in `SLP` status.

**Comment by Fmstrat** [comment]
I've edited the above for clarity on this point and others and made a wiki page: https://github.com/ericaltendorf/plotman/wiki/Plot-statuses

**Comment by drewmullen** [comment]
awesome. thanks a ton, @Fmstrat & @Monstarules . the statuses confused me at first and i suspect that i will not be the last. especially since plotman is exposing status that chia is not (system level).

**Comment by El-Shamsi** [comment]
> Now, using that basic info, let's expand a bit: if your plots seem to be stuck on **SLP** it may have to do with improper or nonexistent staggering. It is best to stagger your plots, else multiple plots might be trying to access the same resources at the same time, which bogs down the disk (especially if you're trying to read and write to the same one), and may make your plots appear to be in a **SLP** status for a long time.

Excellent! 

Thank you

**Comment by RchGrav** [comment]
> > Now, using that basic info, let's expand a bit: if your plots seem to be stuck on **SLP** it may have to do with improper or nonexistent staggering. It is best to stagger your plots, else multiple plots might be trying to access the same resources at the same time, which bogs down the disk (especially if you're trying to read and write to the same one), and may make your plots appear to be in a **SLP** status for a long time.
> 
> Excellent!
> 
> Thank you

Not so fast...   SLP in the first phase is showing the main process, it is sleeping waiting for it's threads to finish.  I don't think you will ever see RUN in phase 1 except briefly when changing subphases.    The main PID is always waiting for its threads to finish.
