### ISSUE TITLE
chia farm summary  show incorrect plots count 

### ISSUE THREAD

**Issue by hipages-guoxu** [ericaltendorf/plotman#224]
`chia farm summary: `
![image](https://user-images.githubusercontent.com/65523876/116912304-9e7e5880-ac7a-11eb-8c7d-7a0d1deb6f84.png)

plots check:

![image](https://user-images.githubusercontent.com/65523876/116912421-c5d52580-ac7a-11eb-8700-bc84e7dc3284.png)

I have started two farms with the same key before, does it will cause this?

**Comment by ericaltendorf** [comment]
you're reporting an issue with chia, but you're reporting it on the plotman
project.  these are not the same project or code base.

**Comment by ericaltendorf** [comment]
Please reopen if I misunderstood.
