### ISSUE TITLE
Rsync error invalid uid

### ISSUE THREAD

**Issue by thomann061** [ericaltendorf/plotman#227]
when running this:
rsync -P testfile.test rsync://username@plot.storage.ip:12000/chia/plots1

i get this error:
ERROR: invalid uid username

SSH keys are working.

**Comment by thomann061** [comment]
The # comment symbol was doing this. The hashtag cannot be used in the rsync config file as listed under the archive wiki.

**Comment by mjsr** [comment]
@thomann061 thanks for saving me a headache. I was already elbows deep into the man page rsyncd.conf(5) and enabling all possible debug.

I've edited the [Archiving wiki page](https://github.com/ericaltendorf/plotman/wiki/Archiving) to move the comments.

From http://manpages.ubuntu.com/manpages/precise/en/man5/rsyncd.conf.5.html:
> Note  that a hash in the middle of a line is used as-is, hence it is not possible to put a comment at the end of a parameter; the  hash  and  following  text  becomes  part  of  the parameter. 

From $ man 5 rsyncd.conf (emphasis mine):

> Any  line beginning with a hash (#) is ignored, as are lines containing only whitespace. **(If a hash occurs after anything other than leading whitespace, it is considered a part of the line’s content.)**

I guess this is fixed.

**Comment by BasilHorowt** [comment]
Thanks for editing the wiki to clean this up @mjsr :)
