### ISSUE TITLE
MacOS Big Sur crashing

### ISSUE THREAD

**Issue by Alqueraf** [ericaltendorf/plotman#239]
I have 2 mac computers plotting and both machines crash when using plotman instead of the GUI.
I did manage to set it up and it was working fine, this has been happening since 4 days ago, not sure if related to Chia being upgraded to 1.1.3.

Using the plotman development branch, didn't see anything relevant on the plotman logs.

How could I troubleshoot this further?

**Comment by BasilHorowt** [comment]
@Alqueraf what's the crash output? I'm running plotman on Big Sur with chia 1.1.3 however I don't use Chia GUI at all

**Comment by Alqueraf** [comment]
Yeah I wasn't using the Chia GUI before, just plotman.
Here is the panic report, I'm not an expert on macs but couldn't find anything relevant

<details>
<summary>Panic report</summary>
Machine-check capabilities: 0x0000000001000c17
 family: 6 model: 62 stepping: 4 microcode: 1070
 signature: 0x306e4
 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
 23 error-reporting banks
Processor 0: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 1: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 2: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 3: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 4: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 5: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 6: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 7: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 8: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 9: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 10: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
Processor 11: IA32_MCG_STATUS: 0x0000000000000005
 IA32_MC7_STATUS(0x41d): 0xfe0332c000010093
 IA32_MC7_ADDR(0x41e):   0x00000004251277c0
 IA32_MC7_MISC(0x41f):   0x0000002450008086
 IA32_MC12_STATUS(0x431): 0xc80334c600800093
 IA32_MC12_MISC(0x433):   0xc900040004000c8c
mp_kdp_enter() timed-out on cpu 5, NMI-ing
mp_kdp_enter() NMI pending on cpus: 0 1 2 3 4 6 7 8 9 10 11
mp_kdp_enter() timed-out during locked wait after NMI;expected 12 acks but received 1 after 11838983 loops in 1750000000 ticks
panic(cpu 5 caller 0xffffff80045c5ed9): "Machine Check at 0xffffff80059af2c1, registers:\n" "CR0: 0x000000008001003b, CR2: 0x0000000112032000, CR3: 0x000000001850e000, CR4: 0x00000000001626e0\n" "RAX: 0x0000000000000020, RBX: 0xffffff93c9ec0df0, RCX: 0x0000000000000001, RDX: 0x0000000000000000\n" "RSP: 0xffffffa1a3253d50, RBP: 0xffffffa1a3253d80, RSI: 0x0000000000000006, RDI: 0xffffff93c9ea7e20\n" "R8:  0x000000000000001c, R9:  0x0000023d490257ca, R10: 0x0000000000000003, R11: 0x000000001850e000\n" "R12: 0xffffff80059c4640, R13: 0xffffff93c9e45980, R14: 0x0000000000000006, R15: 0x00000000000007b0\n" "RFL: 0x0000000000000046, RIP: 0xffffff80059af2c1, CS:  0x0000000000000008, SS:  0x0000000000000000\n" "Error code: 0x0000000000000000\n"@/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/xnu/xnu-7195.101.1/osfmk/i386/trap_native.c:168
Backtrace (CPU 5), Frame : Return Address
0xffffff8004358ad0 : 0xffffff800448e02d 
0xffffff8004358b20 : 0xffffff80045d48e3 
0xffffff8004358b60 : 0xffffff80045c4eda 
0xffffff8004358bb0 : 0xffffff8004432a2f 
0xffffff8004358bd0 : 0xffffff800448d84d 
0xffffff8004358cf0 : 0xffffff800448db43 
0xffffff8004358d60 : 0xffffff8004c9d68a 
0xffffff8004358dd0 : 0xffffff80045c5ed9 
0xffffff8004358ec0 : 0xffffff8004ca141e 
0xffffff8004358ed0 : 0xffffff800443328f 
0xffffffa1a3253d80 : 0xffffff80059a0c03 
0xffffffa1a3253e60 : 0xffffff800599ff57 
0xffffffa1a3253f20 : 0xffffff80045c7272 
0xffffffa1a3253f40 : 0xffffff80044b6379 
0xffffffa1a3253f80 : 0xffffff80044b6548 
0xffffffa1a3253fa0 : 0xffffff800443213e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelCPUPowerManagement(222.0)[88BDDA73-D323-3EF9-8CF4-8F07466EF523]@0xffffff800599e000->0xffffff80059bafff

Process name corresponding to current thread: kernel_task

Mac OS version:
20E232

Kernel version:
Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64
Kernel UUID: BB2FFEBA-7D53-301F-A238-9867CA51276F
KernelCache slide: 0x0000000004200000
KernelCache base:  0xffffff8004400000
Kernel slide:      0x0000000004210000
Kernel text base:  0xffffff8004410000
__HIB  text base: 0xffffff8004300000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 2463878194738
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000023daa976022
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0004b054a4941de0 0x0000000000000000
last started kext at 11099947646: >AudioAUUC	1.70 (addr 0xffffff7f9d78c000, size 12288)
loaded kexts:
com.rim.driver.BlackBerryVirtualPrivateNetwork	1.0.18
>AudioAUUC	1.70
>AGPM	122
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@fileutil	20.036.15
@filesystems.autofs	3.0
>!AUpstreamUserClient	3.6.8
>!AMCCSControl	1.14
@kext.AMDFramebuffer	4.0.4
@kext.AMDRadeonX4000	4.0.4
@kext.AMDRadeonServiceManager	4.0.4
>!AGraphicsDevicePolicy	6.2.9
@AGDCPluginDisplayMetrics	6.2.9
>pmtelemetry	1
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!AHDAHardwareConfigDriver	283.15
|IO!BSerialManager	8.0.4d18
>!AHDA	283.15
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>!AMGPUPowerControl	6.2.9
@kext.AMD7000!C	4.0.4
>eficheck	1
>!AThunderboltIP	4.0.3
>!A!IMCEReporter	115
>!AFIVRDriver	4.1.0
>!ALPC	3.1
>ACPI_SMC_PlatformPlugin	1.0.0
>!A!ISlowAdaptiveClocking	4.0.0
|IO!BUSBDFU	8.0.4d18
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.100.11
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@filesystems.apfs	1677.100.114
>AirPort.BrcmNIC	1400.1.1
|!ABCM5701Ethernet	11.0.0
>!AAHCIPort	346.100.2
@private.KextAudit	1.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!AACPIEC	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AAPIC	1.7
>!A!ICPUPowerManagementClient	222.0.0
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	311
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
>!A!ICPUPowerManagement	222.0.0
@kext.triggers	1.0
>!ASMBus!C	1.0.18d1
@kext.AMDRadeonX4030HWLibs	1.0
|IOAccelerator!F2	442.9
@kext.AMDRadeonX4000HWServices	4.0.4
|IOSerial!F	11
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOAVB!F	940.4
|IOEthernetAVB!C	1.1.0
@plugin.IOgPTPPlugin	980.4
>!AGraphicsControl	6.2.9
>!ABacklightExpert	1.1.0
|IONDRVSupport	585.1
>!AHDA!C	283.15
|IOHDA!F	283.15
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
@kext.AMDSupport	4.0.4
@!AGPUWrangler	6.2.9
@!AGraphicsDeviceControl	6.2.9
|IOGraphics!F	585.1
>IOPlatformPluginLegacy	1.0.0
>!ASMBusPCI	1.0.14d1
>!AThunderboltEDMSink	5.0.3
>!AThunderboltDPOutAdapter	8.1.4
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOSlowAdaptiveClocking!F	1.0.0
|Broadcom!BHost!CUSBTransport	8.0.4d18
|IO!BHost!CUSBTransport	8.0.4d18
|IO!BHost!CTransport	8.0.4d18
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
>!AThunderboltDPInAdapter	8.1.4
>!AThunderboltDPAdapter!F	8.1.4
>!AThunderboltPCIDownAdapter	4.1.1
>!ABSDKextStarter	3
|IOSurface	290.7
@

</details>

**Comment by BasilHorowt** [comment]
whoa I didn't realize it was a full machine crash, I thought it was just python crashing 😳 

i know nothing about diagnosing kernel panics, but given `com.apple.driver.AppleIntelCPUPowerManagement` is there in the log it might be worth it to try a PRAM/NVRAM/SMC reset.   I feel like I always see that suggested and generally is of suspicious value, but who knows.  Would be worth temporarily disconnecting all peripherals and see if it still happens too.

**Comment by Alqueraf** [comment]
Ok, will try this out, thanks.
Closing as I don't think it's related to plotman, will post back the issue if I can find it.
