### ISSUE TITLE
Can't start plotman in ubuntu (20.04)

### ISSUE THREAD

**Issue by igorcarrasco** [ericaltendorf/plotman#240]
$ plotman plot
```python-traceback
...starting plot loop
Traceback (most recent call last):
  File "/usr/local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/plotman/plotman.py", line 143, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/usr/local/lib/python3.8/dist-packages/plotman/manager.py", line 130, in maybe_start_new_plot
    p = subprocess.Popen(plot_args,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia'
```

I should note I had to install pip3 and install plotman with it, not sure if it matters.
Would appreciate any help.

**Comment by igorcarrasco** [comment]
I tried executing it from these paths:
~/chia-blockchain/chia/daemon
~/chia-blockchain
But same error

**Comment by SpLord** [comment]
source ~/chia-blockchain/activate 
afterwards you can use plotman

**Comment by altendky** [comment]
https://github.com/ericaltendorf/plotman#installation

You can also use `@development` instead of `@main` if you want the latest bug fixes and features.

Also, mostly don't use your system pip.  Definitely do not use pip as root, such as with sudo or otherwise.

**Comment by BasilHorowt** [comment]
@igorcarrasco did this work for you?  Going to close because it looks like you simply need to `. ./activate` the venv
