### ISSUE TITLE
install under OS X failed

### ISSUE THREAD

**Issue by nerle** [ericaltendorf/plotman#244]
Hello,

1. I know its not fully supported under os x but it would be nice :)

While running the install via pip I get the error:     

```
Uninstalling plotman-0.2:
      Successfully uninstalled plotman-0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.3 requires pyqt5<5.13, which is not installed.
spyder 4.2.3 requires pyqtwebengine<5.13, which is not installed.
Successfully installed appdirs-1.4.4 attrs-20.3.0 desert-2020.11.18 marshmallow-3.11.1 mypy-extensions-0.4.3 pendulum-2.1.2 plotman-0.2 psutil-5.8.0 python-dateutil-2.8.1 pytzdata-2020.1 pyyaml-5.4.1 six-1.15.0 texttable-1.6.3 typing-extensions-3.10.0.0 typing-inspect-0.6.0
```

I installed spyder using homebrew and it worked. I also installed pyqt5 and  pyqtwebengie via pip, which results in the following error:

```
(base) nerle@MacBook-Pro-3 chia % pip install PyQtWebEngine
Collecting PyQtWebEngine
  Downloading PyQtWebEngine-5.15.4-cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel.whl (186 kB)
     |████████████████████████████████| 186 kB 2.9 MB/s 
Collecting PyQtWebEngine-Qt5>=5.15
  Downloading PyQtWebEngine_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (77.9 MB)
     |████████████████████████████████| 77.9 MB 31.7 MB/s 
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.8.1-cp38-cp38-macosx_10_9_x86_64.whl (63 kB)
     |████████████████████████████████| 63 kB 9.3 MB/s 
Collecting PyQt5>=5.15.4
  Downloading PyQt5-5.15.4-cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel.whl (7.0 MB)
     |████████████████████████████████| 7.0 MB 26.0 MB/s 
Collecting PyQt5-Qt5>=5.15
  Downloading PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (40.5 MB)
     |████████████████████████████████| 40.5 MB 11.4 MB/s 
Installing collected packages: PyQt5-sip, PyQt5-Qt5, PyQtWebEngine-Qt5, PyQt5, PyQtWebEngine
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.3 requires pyqt5<5.13, but you have pyqt5 5.15.4 which is incompatible.
spyder 4.2.3 requires pyqtwebengine<5.13, but you have pyqtwebengine 5.15.4 which is incompatible.
```

Now my question - the installation is not possible because of different pre requirements. It would be fine if plotman could work with actual versions but I understand that plotman is not responsible for the current error. 

Anyone solved it before? With env perhaps?

best regards Dirk

**Comment by ericaltendorf** [comment]
hmm, i know some folks here are using plotman on OSX.  have you been able
to find any of them to get feedback on this?

**Comment by nerle** [comment]
No unfortunately not - asked at Keybase too.

**Comment by altendky** [comment]
It seems you are installing into an env that already has other stuff installed and there is some conflict.  If you installed chia from source it should have created an env that you can use.  If not then create one such as `python3 -m venv myvenv`.  This will create a directory named `myvenv`.  You can then either `myvenv/bin/plotman` to run it or `source myvenv/bin/activate` and then `plotman`.  Lots of options and combinations depending on how you did everything else.  But, we can get there.

**Comment by nerle** [comment]
Thank you! I created a new venv and could install plotman without the errors I mentioned above.
