### ISSUE TITLE
Archive only runs when 'plotman interactive' is running

### ISSUE THREAD

**Issue by prpatel** [ericaltendorf/plotman#245]
I have "plotman plot" running in a "screen" cmd. It's working great, starting up plot jobs.

I noticed that multiple finished plots in the dst dir were not being transferred to the rsync server (timestamp shows they were created several hours ago)

I started "plotman interactive" to troubleshoot, and immediately an rsync job fired up and started (and completed) the transfer successfully. I quit "plotman interactive", and again, no rsync running for the remaining finished plots, once the previous one was done.

I tried to run "plotman archive" but it didn't seem to start up any rsync jobs either, output:

...starting archive loop
Sleeping 60s until next iteration...
Sleeping 60s until next iteration...

I'd prefer not to keep a shell open to run "plotman interactive" so that rsync jobs run. Did I miss something obvious, or how do I troubleshoot this, or is this a bug :)

**Comment by VercauterenK** [comment]
can you show your config i cant setup mine

**Comment by thomann061** [comment]
Plotman interactive has to stay open for the archive to continuously work. I have not tried 'plotman archive'. I agree though there should be a more standard way of running plots and the archive.

**Comment by prpatel** [comment]
> Plotman interactive has to stay open for the archive to continuously work. I have not tried 'plotman archive'. I agree though there should be a more standard way of running plots and the archive.

@thomann061 it appears as if the code is there for plotman.py to run "plotman archive". Perhaps someone who knows Python better than me can fix whatever is wrong.

**Comment by thomann061** [comment]
From looking at the code, it doesn't look like the archive command ever gets sent to the shell. It looks like it was setup with the intent to run it, but was never implemented. However, the plotman interactive, shows the code being sent to the shell.

This function returns the command, but the command is never used: https://github.com/ericaltendorf/plotman/blob/5788e7fa2df2186ccb94db2d388766f9d52116a4/src/plotman/plotman.py#L183

However it is used in plotman interactive:
https://github.com/ericaltendorf/plotman/blob/5788e7fa2df2186ccb94db2d388766f9d52116a4/src/plotman/interactive.py#L130-L142

**Comment by thomann061** [comment]
I think this has been taken care of- #96

**Comment by prpatel** [comment]
You are correct, looks like that issue fixed it 
Duplicate of #96
