### ISSUE TITLE
Archive (Rsync) on non-standard SSH Port

### ISSUE THREAD

**Issue by aboukouris** [ericaltendorf/plotman#246]
Hello,

I am new to plotman (are'nt we all?) and I'm looking a way to make the archive to work on a non-standard port for SSH.
It's very common security precaution to change the SSH port so I would love not to expose my farmer's 22 port to the internet.

Rsync work with -e "ssh -p 1111" parameter where 1111 is the SSH port.

I tried to find any answer here, but I onlt found about rsync port 12000 on #169 

Thank you,
and happy ploting :)
Alex

**Comment by ericaltendorf** [comment]
That's a good idea, but unfortunately not currently configurable, but we do have issue #6 to make this better.  For now your only option is probably to go into the code and hack in the `-p` parameter where the code calls `ssh`.

**Comment by steinbachio** [comment]
You can use `$HOME/.ssh/config` and add
```
Host farmer01
    HostName farmer01
    User username
    Port 1111
```

**Comment by aboukouris** [comment]
Thank you both @ericaltendorf  and @steinbachio.
