### ISSUE TITLE
should kill the process when the iowait is too long?

### ISSUE THREAD

**Issue by jjhesk** [ericaltendorf/plotman#255]
we have experienced that iowait exceeded more than 7 hours... is that dead for sure?

**Comment by altendky** [comment]
At that point it is entirely about the `chia plots create` command so this isn't a plotman issue.  Perhaps ask in #support or #plotting-hardware on the Chia keybase.

**Comment by jjhesk** [comment]
i found out that iowait too long will lockup the progress of the actual plotting and they will have to do with DSK status. @altendky maybe we should take a closer look if that is possible to kill the process or suspend them until there are DSK capacity io available.
