### ISSUE TITLE
[Question] Changing configuration without stopping plot process

### ISSUE THREAD

**Issue by piotrkochan** [ericaltendorf/plotman#280]
Is there any way to make changes in the config without need to stop plotting?
I tried to add more buffer but it Plotman still uses old value. 
Scheduling on the other hand seems to be applied automatically.

**Comment by BasilHorowt** [comment]
To be clear, you don't have to stop any plotting to reload plotman to load the new config, this is noted in the [FAQ](https://github.com/ericaltendorf/plotman/wiki/FAQ).  If you are interested in plotman "watching" the config file so you don't have to restart, subscribe to this issue: https://github.com/ericaltendorf/plotman/issues/254
