### ISSUE TITLE
Proper way to change parameters in plotman.yaml file while plotman is already running

### ISSUE THREAD

**Issue by palpen** [ericaltendorf/plotman#281]
I'm testing my setup with basic scheduling parameters to make sure that everything is working. Now that I've confirmed this, I'd like to increase the tmpdir_max_jobs parameter to allow for more plots to be plotted or perhaps I'd like to add additional tmp ssd drives. However, I do not want to interrupt plots that I'm currently generating. 

How does one edit the plotman.yaml file and apply those changes without interrupting plotting from a previous setting? Can I just run `plotman plot` again after updating the parameters in the yaml file?

**Comment by VercauterenK** [comment]
Just change the file. Then if plotman interactive is running pres ctrl-c and then type plotman interactive.

**Comment by palpen** [comment]
Thanks. I have plotman plot running and escaped that and restarted it again after changing the config. This seem to work.

**Comment by BasilHorowt** [comment]
Sounds like it is working @palpen? As a note, `q` key can be used to quit instead of ctrl-c though probably pretty identical in functionality

**Comment by palpen** [comment]
Thanks Basil---I use `plotman plot` to start the process so I must ctrl-c to stop it (or kill the PID associated with the job).

**Comment by BasilHorowt** [comment]
Yes but make sure you have tried "plotman interactive" if you don't know about it.
