### ISSUE TITLE
How to setup in docker?

### ISSUE THREAD

**Issue by Forusim** [ericaltendorf/plotman#293]
Hello, currently I run the full node via official chia docker in Unraid.
I would like to setup a plotter docker with your manager.

My Dockerfile:
```
FROM ubuntu:latest

ARG BRANCH="latest"                                                      
ARG DEBIAN_FRONTEND="noninteractive"
COPY dpkg_excludes /etc/dpkg/dpkg.cfg.d/excludes 

RUN apt-get update && apt-get install --no-install-recommends -y \
    curl wget jq tar unzip ca-certificates git openssl lsb-release sudo python3 python3-pip python3-dev python3.8-venv python3.8-distutils python-is-python3 \
    rsync

RUN git clone --branch ${BRANCH} https://github.com/Chia-Network/chia-blockchain.git \
 && cd chia-blockchain \
 && git submodule update --init mozilla-ca \
 && chmod +x install.sh \
 && ./install.sh        

RUN pip3 install git+https://github.com/ericaltendorf/plotman@main

WORKDIR /chia-blockchain/venv/bin  
VOLUME /config

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["bash", "/entrypoint.sh"]
```

My entrypoint.sh:
```
#!/bin/bash

CONFDIR=/config
GENDIR=/root/.config/plotman

if [[ ! -f "$CONFDIR/plotman.yaml" ]]; then
  plotman config generate
  cp $GENDIR/plotman.yaml $GENDIR/plotman.yaml.default
  cp $GENDIR/plotman.yaml.default $CONFDIR
  mv $GENDIR/plotman.yaml $CONFDIR
fi
ln -s $CONFDIR/plotman.yaml $GENDIR/plotman.yaml

cd /chia-blockchain
. ./activate

while true; do sleep 30; done;
```

When I try to start `plotman plot` I get this error `FileNotFoundError: [Errno 2] No such file or directory: 'chia'`
I tried to activate from docker shell `bash -c 'source /chia-blockchain/activate`, but it did´t help.
I know that you are telling not to run with root user, but how else I can accomplish this?
I it possible, that you add a parameter to plotman.yaml to optionally point to the `/chia-blockchain/venv/bin/chia` location?

**Comment by chadmccune** [comment]
This is what I'm using and it works on my unraid server

`FROM ubuntu:focal

RUN apt update && \
    apt -y install git sudo

RUN export DEBIAN_FRONTEND=noninteractive

RUN ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime
RUN apt -y install tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata
RUN apt -y install lsb-core    

RUN git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules

WORKDIR /chia-blockchain

RUN sh install.sh

RUN . ./activate && pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main && chia init

CMD . ./activate && plotman plot
`

I use bind mounts for /root/.config/plotman.yaml, /chialogs, /mnt/tmp00 and /mnt/dst

**Comment by Forusim** [comment]
Ok, so most important part is `. ./activate && plotman plot`?
I cannot `. ./activate ` separately and then invoke plotman plot whenever I want?

**Comment by chadmccune** [comment]
> Ok, so most important part is `. ./activate && plotman plot`?
> I cannot `. ./activate ` separately and then invoke `plotman plot` whenever I want?

I'm not a docker expert, I fiddle around until I get something to work and then just leave it alone :)

**Comment by Forusim** [comment]
@chadmccune I sorted it out to a degree I am comfortable with. Thanks again.
