### ISSUE TITLE
Ubuntu Ask Password every time plotman interactive run or refresh (every 20 seconds)

### ISSUE THREAD

**Issue by aboukouris** [ericaltendorf/plotman#296]
Hello,

I am not sure if this is a plotman issue, but maybe someone else has face this totaly strange issue:

When I login to ubuntu via SSH and execute "plotman interactive" ask me for password.
If I enter the right password, plotman interactive run until the next refresh (20s) when ask for password again.
If I enter wrong password (or enter) 3 times, it run again (!!) until the next refresh that ask for password again.

If I run plotman interactive from local terminal it works fine, without asking for password. If from the terminal I ssh to localhost, it has the strange behaviour above (ask for password).

This happened only to ubuntu and I'm runing version 20.04.2 LTS. In centos linux I had no problems like this.
System is clean installation with chia, plotman, and installed ssh with apt-get.

I also tried to find similar issues, but I had no luck.

Thank you in advance,

Alex

**Comment by aboukouris** [comment]
After a lot of searching, and installing another system with the same exactly configuration I came close to the problem, and solve it.

I close the issue and leave it here, in case someone else face the same problem. It's not a plotman issue, it's something strange with the ssh keys on ubuntu.

Why: In every refresh, plotman tries to get the free disk space on archive (via rsync). That's why it was asking for password. The password was for the farming machine.

How problem occurs: When you install passwordless ssh (with public key) if you do it from the terminal it thinks it's different from the ssh. 

How to solve the problem: Install ssh key remotely again with the following commands, after you ssh to your server
ssh-keygen
ssh-copy-id username@farmer_ip

**Comment by altendky** [comment]
Thanks for following up and sharing your solution.  `:]`
