### ISSUE TITLE
No way to pause staggering.

### ISSUE THREAD

**Issue by Emperornero** [ericaltendorf/plotman#306]
Hello,

Unfortunately I am terrible at coding, however, we definitely need a way to pause staggering.

Currently, plotman runs indefinitely, so the only way to stop it from generating plots is to lose all the progress you have on your current plots incase you have to change something for the configuration.

I think we can all agree that losing hours of progress on multiple plots just to change the configuration is a terrible UX and design decision.

Can we get a way to pause staggering while letting the plotting process to continue to run?

Thanks.

**Comment by climbingblake** [comment]
I was wondering this same thing, as things are running well for me, but I want to upgrade chia, and dont really want to stop everything(aka lose progress), just for a version bump

**Comment by thomann061** [comment]
> Hello,
> 
> Unfortunately I am terrible at coding, however, we definitely need a way to pause staggering.
> 
> Currently, plotman runs indefinitely, so the only way to stop it from generating plots is to lose all the progress you have on your current plots incase you have to change something for the configuration.
> 
> I think we can all agree that losing hours of progress on multiple plots just to change the configuration is a terrible UX and design decision.
> 
> Can we get a way to pause staggering while letting the plotting process to continue to run?
> 
> Thanks.

If you use `plotman interactive` you can press p to toggle whether new plots will spawn based on your configuration.

**Comment by altendky** [comment]
Yes, there's `p`.  You can also quit.  You can also update chia while plotman is running.  I do all three and none of them lose hours of plots.  The plot processes are independent of plotman.

Also, it's not pausing of staggering, just pausing of launching plots.  The stagger options are just some of the overall set of limits that must be satisfied prior to launching a plot.

**Comment by thomann061** [comment]
> Yes, there's `p`. You can also quit. You can also update chia while plotman is running. I do all three and none of them lose hours of plots. The plot processes are independent of plotman.
> 
> Also, it's not pausing of staggering, just pausing of launching plots. The stagger options are just some of the overall set of limits that must be satisfied prior to launching a plot.

Oh that makes sense, I did not realize I could update chia while plotman is running.

**Comment by Emperornero** [comment]
> > Hello,
> > Unfortunately I am terrible at coding, however, we definitely need a way to pause staggering.
> > Currently, plotman runs indefinitely, so the only way to stop it from generating plots is to lose all the progress you have on your current plots incase you have to change something for the configuration.
> > I think we can all agree that losing hours of progress on multiple plots just to change the configuration is a terrible UX and design decision.
> > Can we get a way to pause staggering while letting the plotting process to continue to run?
> > Thanks.
> 
> If you use `plotman interactive` you can press p to toggle whether new plots will spawn based on your configuration.

Interesting.  I can't find this in the documentation.

When I killed the plotman program, then check again with `plotman status` it would still show the stagger timer as going, and I didn't want more plots to start.

Might be good to put this information somewhere. I'll close the issue.
