### ISSUE TITLE
Bug: After config dst change, old (no longer configured) dst is still being used for new plots

### ISSUE THREAD

**Issue by gumba4** [ericaltendorf/plotman#31]
Thanks for plotman!
I noticed a bug:
I started plotman (interactive) with two dst folders, say dst01 and dst02. Plotting went fine, plots were created etc.
Then I removed dst01 folder from the config, leaving only dst02.
I restarted plotman (interactive).
Now I noticed that still a plot command with "-d dst01" was generated. Though only one dst is (correctly) shown in plotman (interactive).
I suspect this is due to method "dstdirs_to_youngest_phase" in manager.py. This method takes the running jobs (including ones with dst01 from before the config update) and their dst directories for selection. However these dst directories should be filtered to not include any not in config.

How to fix:
In manager.py, variable dir2ph should not contain dst entries which are not in the config.

**Comment by ericaltendorf** [comment]
Thanks for the detailed report!  This would have bitten me today and given me a debugging headache had you not filed this.  Working on a fix now.

**Comment by BasilHorowt** [comment]
Going to close this as it appears it was resolved a few months ago
