### ISSUE TITLE
Double count of jobs

### ISSUE THREAD

**Issue by D4rk4** [ericaltendorf/plotman#337]
> 
> $ plotman status
>  plot id    k              tmp              dst   wall   phase    tmp       pid   stat     mem   user    sys     io
> fc950a1b   32   /srv/chia/fast   /srv/chia/dest   6:58     3:1   236G   4176527    SLP    2.6M     0s     0s     0s
> fc950a1b   32   /srv/chia/fast   /srv/chia/dest   6:58     3:1   236G   4176528    DSK   18.4G   6:01   0:07   1:23
> a9f3ea7a   32   /srv/chia/fast   /srv/chia/dest   9:40     4:0   176G   1317240    SLP    2.6M     0s     0s     0s
> a9f3ea7a   32   /srv/chia/fast   /srv/chia/dest   9:40     4:0   176G   1317241    RUN   17.7G   8:16   0:13   4:19

Chia from deb package:

> $ dpkg -l | grep chia; which chia; ls -lash `which chia`
> ii  chia-blockchain                               1.1.4                                amd64        GUI for Chia Blockchain
> /usr/local/bin/chia
> 512 lrwxrwxrwx 1 root staff 64 мая  8 17:57 /usr/local/bin/chia -> /usr/lib/chia-blockchain/resources/app.asar.unpacked/daemon/chia

**Comment by altendky** [comment]
Thanks.  I'll try to figure this out tonight.  I do see #330 but would like to understand this a bit better.  I'm a bit confused why this is just popping up now.

**Comment by juliencampy** [comment]
I got a fix on my computer but I won't create a pull request for this as this is a hack at best.
It is adding this filter in the get_running_jobs function :

`proc.cpu_times().user == 0.0`

It looks counter intuitive, but only the proc with this attributes at 0 does have open_files associated with it. I am not a linux nor python expert so I have no idea why ...

It works here but I guess that will not be the case on computer not affected by the issue.
A cleaner way would be to use the ppid() of the proc, but I can't make it work atm.

Cheers.

**Comment by lexzz** [comment]
I'm seeing the same issue on the development branch

**Comment by rafaelsteil** [comment]
> I got a fix on my computer but I won't create a pull request for this as this is a hack at best.
> It is adding this filter in the get_running_jobs function :
> 
> `proc.cpu_times().user == 0.0`
> 
> It looks counter intuitive, but only the proc with this attributes at 0.0 does have open_files associated with it. I am not a linux nor python expert so I have no idea why ...
> 

I'd say it was more of a coincidence than anything else. 

> It works here but I guess that will not be the case on computer not affected by the issue.
> A cleaner way would be to use the ppid() of the proc, but I can't make it work atm.
> 

Relying on the parent pid can get tricky very quickly and doesn't indicate anything bad or good per se. A job started by `plotman plot` will have it's pid as parent _as long as `plotman plot` is running_. If you stop the plotter (a perfect valid scenario) the jobs will then return `1` as their parent PID.

**Comment by rafaelsteil** [comment]
> > $ plotman status
> > plot id    k              tmp              dst   wall   phase    tmp       pid   stat     mem   user    sys     io
> > fc950a1b   32   /srv/chia/fast   /srv/chia/dest   6:58     3:1   236G   4176527    SLP    2.6M     0s     0s     0s
> > fc950a1b   32   /srv/chia/fast   /srv/chia/dest   6:58     3:1   236G   4176528    DSK   18.4G   6:01   0:07   1:23
> > a9f3ea7a   32   /srv/chia/fast   /srv/chia/dest   9:40     4:0   176G   1317240    SLP    2.6M     0s     0s     0s
> > a9f3ea7a   32   /srv/chia/fast   /srv/chia/dest   9:40     4:0   176G   1317241    RUN   17.7G   8:16   0:13   4:19

@D4rk4 One thing that I noticed is that, despite that some columns are the same, other's aren't, which is curious. Can you confirm that when you saw this issue you actually had only two "real" jobs instead of 4?

**Comment by D4rk4** [comment]
@rafaelsteil it's 2 jobs, correct job info displayed in the second row of each plot ID

**Comment by altendky** [comment]
If you could try out https://github.com/ericaltendorf/plotman/pull/418, that'd be great.  Follow the regular readme installation but use `git+https://github.com/altendky/plotman@skip_matching_plot_process_parents` as the url.

**Comment by juliencampy** [comment]
@altendky Works well for me, found a minor bug though, some temporary file (2-3 each time) are not removed after a plotman kill.

**Comment by altendky** [comment]
@juliencampy yeah, the plotter doesn't keep all the files open all the time I think and that's how we detect.  There's some improvement to be done there for sure.

**Comment by D4rk4** [comment]
Work fine for me
