### ISSUE TITLE
[Proposal] Improve analyze

### ISSUE THREAD

**Issue by rafaelsteil** [ericaltendorf/plotman#348]
### Motivation
In its current implementation, `plotman analyze` shows a rather limited amount of information that doesn't necessarily provides a good set of useful data to the user. We should extend it by adding additional information that can be extrapolated from the log files and disk stats. 

### Command line arguments
- Display time in seconds / minutes / hours
- Number of days to analyze
- Specific file to analyze (default should be the entire log dir)
- Export to CSV (for keeping historical or comparative data)
- Per day details (instead of a summary of all)
- Size notation in 1000 or 1024 ( `(M|G|T)i?B`)

### Information to show
- How many log files were analyzed
- Location of the log files
- Disclaimer that data accuracy depends on log files (e.g, can't analyze stuff without logs)
- Number of plots in the last 24h
- Number of plots created in the last `n` days
- Plots per day
- Average time per plot
- Average time per disk
- Average time per phase
- TiB plotted per day
- Per drive stats: used and total space, percent used, number of plots 

### How to show the information
There's only so much we can do with textual representation of information in a terminal. A per line stat and an aggregated table may be clear enough. 

> _This is a work in progress_

```
Logs directory: ~/chia/logs.
Analyzed 117 log files ceated in the last 7 days. 


Plots created in the last 24h: 7
Plots created in the last 7 days: 31
Average plots created per day: 4.42
Average time per plot: 271 min (4.51 hours)
Total size plotted per day: 446GB

-------------------------------------------
DRIVE 	     TYPE   PLOTS   USED    AVAIL
-------------------------------------------
/mnt/tmp1    temp    	-   713GB    217GB
/mnt/tmp2    temp    	-   1.7TB    300GB

/mnt/farm1   farm      91   9.2TB    4.8TB
/mnt/farm2   farm      17   1.7TB   12.3TB
/mnt/farm3   farm    	7   707GB   13.3TB
-------------------------------------------

Tip: "plotman status" shows currently running jobs. 

```

**Comment by altendky** [comment]
Well...  I know I've seen TUi plotting libraries...  but yeah.  `:]`

Big list of stuff to do.  Do you think the standard deviation isn't useful?  I would think it would indicate successful staggering, at least to some degree.  Running averages and notes of configuration change points would be good.  At least if the log files hold the command line parameters.  Though in general I imagine we could be creating side-car files or otherwise logging more information (like per line time stamps and config and so on).

**Comment by rafaelsteil** [comment]
To be fair standard deviation isn't in the list only because I forgot to add it 🤦 . I believe that the information should be presented in a friendly manner that the average person can understand (e.g, keep `μ` and `σ` out of it). For those who want more control, exporting to CSV will give them the change to play with the data.

**Comment by aaroneden** [comment]
@rafaelsteil  have you started work on this?  Want an extra set of hands?

**Comment by rafaelsteil** [comment]
@aaroneden I'm just getting started, but so far it's just a bunch of random stuff (so maybe I haven't started yet 🤔 ). Feel free to jump it 🙌 . I don't have a specific plan in mind, but it looks like this can be broken into several small PRs since many metrics can be independent of each other, with one or another thing shared (e.g, log parsing would be one of them. 

One thing to consider: do we just make one giant class with everything in there (much like the current `analyzer.py`, or make it more modular where new analyzers live in their own `.py` files and on startup are registered (literally just adding to a list or something)?

**Comment by aaroneden** [comment]
I agree on multiple PRs.  Makes sense.

W/r/t Giant Class — I would suggest we start here and if/when it becomes too big we can refactor into smaller chunks.

I like the idea of making the analyzers configurable on startup, but that sounds like a separate story.

Best,
Aaron

**Comment by rafaelsteil** [comment]
FWIW I opened a PR that adds a log parsing class https://github.com/ericaltendorf/plotman/pull/532
