### ISSUE TITLE
chia-blockchain 1.1.6.dev0 requires click==7.1.2, but you have click 8.0.0 which is incompatible.

### ISSUE THREAD

**Issue by jonfatino** [ericaltendorf/plotman#390]
**Describe the bug**
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chia-blockchain 1.1.6.dev0 requires click==7.1.2, but you have click 8.0.0 which is incompatible.
**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Install CHIA on fresh ubuntu 20.04 box
cd /root
git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules
cd /root/chia-blockchain
chmod +x ./install.sh
./install.sh
. ./activate
chia init

2. Try and install plotman
cd /root/chia-blockchain
. ./activate
pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main

**Expected behavior**
Obviously it run 

**System setup:**
- Ubuntu 20.04 LTS

**Config**
Not installed yet 

</details>

**Additional context & screenshots**
Terminal log

root@ubuntu:~#         cd /root/chia-blockchain
root@ubuntu:~/chia-blockchain#         . ./activate
(venv) root@ubuntu:~/chia-blockchain# pip install --force-reinstall git+https://github.com/ericaltendorf/plotman@main
Collecting git+https://github.com/ericaltendorf/plotman@main
  Cloning https://github.com/ericaltendorf/plotman (to revision main) to /tmp/pip-req-build-ap4in88n
  Running command git clone -q https://github.com/ericaltendorf/plotman /tmp/pip-req-build-ap4in88n
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting pendulum
  Downloading pendulum-2.1.2-cp38-cp38-manylinux1_x86_64.whl (155 kB)
     |████████████████████████████████| 155 kB 36.2 MB/s 
Collecting texttable
  Downloading texttable-1.6.3-py2.py3-none-any.whl (10 kB)
Collecting desert
  Downloading desert-2020.11.18-py3-none-any.whl (9.5 kB)
Collecting attrs
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting psutil~=5.8
  Downloading psutil-5.8.0-cp38-cp38-manylinux2010_x86_64.whl (296 kB)
     |████████████████████████████████| 296 kB 80.8 MB/s 
Collecting marshmallow
  Downloading marshmallow-3.12.1-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 35.6 MB/s 
Collecting click
  Downloading click-8.0.0-py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 48.0 MB/s 
Collecting pyyaml
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting typing-inspect
  Downloading typing_inspect-0.6.0-py3-none-any.whl (8.1 kB)
Collecting pytzdata>=2020.1
  Downloading pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
     |████████████████████████████████| 489 kB 116.7 MB/s 
Collecting python-dateutil<3.0,>=2.6
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 104.5 MB/s 
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typing-extensions>=3.7.4
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Building wheels for collected packages: plotman
  Building wheel for plotman (PEP 517) ... done
  Created wheel for plotman: filename=plotman-0.3-py3-none-any.whl size=56473 sha256=3a010a5e4a5f9c091fd2f04bde32554d29d38c921011955dc9d3c27bcb93e6f5
  Stored in directory: /tmp/pip-ephem-wheel-cache-5qd39b79/wheels/6e/4e/4d/284bb2756fdd9abdf6cbf8cc207251b72e1c81f806378c26fe
Successfully built plotman
Installing collected packages: typing-extensions, six, mypy-extensions, typing-inspect, pytzdata, python-dateutil, marshmallow, attrs, texttable, pyyaml, psutil, pendulum, desert, click, appdirs, plotman
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.0
    Uninstalling typing-extensions-3.10.0.0:
      Successfully uninstalled typing-extensions-3.10.0.0
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
  Attempting uninstall: attrs
    Found existing installation: attrs 21.2.0
    Uninstalling attrs-21.2.0:
      Successfully uninstalled attrs-21.2.0
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.4.1
    Uninstalling PyYAML-5.4.1:
      Successfully uninstalled PyYAML-5.4.1
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chia-blockchain 1.1.6.dev0 requires click==7.1.2, but you have click 8.0.0 which is incompatible.
Successfully installed appdirs-1.4.4 attrs-21.2.0 click-8.0.0 desert-2020.11.18 marshmallow-3.12.1 mypy-extensions-0.4.3 pendulum-2.1.2 plotman-0.3 psutil-5.8.0 python-dateutil-2.8.1 pytzdata-2020.1 pyyaml-5.4.1 six-1.16.0 texttable-1.6.3 typing-extensions-3.10.0.0 typing-inspect-0.6.0
(venv) root@ubuntu:~/chia-blockchain#

**Comment by jonfatino** [comment]
If you remove --force-reinstall it will work.


`(venv) root@ubuntu:~/chia-blockchain# pip install git+https://github.com/ericaltendorf/plotman@main                  
Collecting git+https://github.com/ericaltendorf/plotman@main
  Cloning https://github.com/ericaltendorf/plotman (to revision main) to /tmp/pip-req-build-jk0od5k6
  Running command git clone -q https://github.com/ericaltendorf/plotman /tmp/pip-req-build-jk0od5k6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pendulum in ./venv/lib/python3.8/site-packages (from plotman==0.3) (2.1.2)
Requirement already satisfied: desert in ./venv/lib/python3.8/site-packages (from plotman==0.3) (2020.11.18)
Requirement already satisfied: texttable in ./venv/lib/python3.8/site-packages (from plotman==0.3) (1.6.3)
Requirement already satisfied: psutil~=5.8 in ./venv/lib/python3.8/site-packages (from plotman==0.3) (5.8.0)
Requirement already satisfied: attrs in ./venv/lib/python3.8/site-packages (from plotman==0.3) (21.2.0)
Requirement already satisfied: pyyaml in ./venv/lib/python3.8/site-packages (from plotman==0.3) (5.4.1)
Requirement already satisfied: click in ./venv/lib/python3.8/site-packages (from plotman==0.3) (8.0.0)
Requirement already satisfied: marshmallow in ./venv/lib/python3.8/site-packages (from plotman==0.3) (3.12.1)
Requirement already satisfied: appdirs in ./venv/lib/python3.8/site-packages (from plotman==0.3) (1.4.4)
Requirement already satisfied: typing-inspect in ./venv/lib/python3.8/site-packages (from desert->plotman==0.3) (0.6.0)
Requirement already satisfied: pytzdata>=2020.1 in ./venv/lib/python3.8/site-packages (from pendulum->plotman==0.3) (2020.1)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in ./venv/lib/python3.8/site-packages (from pendulum->plotman==0.3) (2.8.1)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.8/site-packages (from python-dateutil<3.0,>=2.6->pendulum->plotman==0.3) (1.16.0)
Requirement already satisfied: typing-extensions>=3.7.4 in ./venv/lib/python3.8/site-packages (from typing-inspect->desert->plotman==0.3) (3.10.0.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./venv/lib/python3.8/site-packages (from typing-inspect->desert->plotman==0.3) (0.4.3)
(venv) root@ubuntu:~/chia-blockchain# plo
plog     plotman  `

**Comment by altendky** [comment]
There are a couple other tickets for this I think.  Anyways, v0.3.1 was just released and should address this.

**Comment by advanderveer** [comment]
Yep, tried installing it today again and it worked in one go. Thank you!

**Comment by altendky** [comment]
Sure thing.  `:]`
