### ISSUE TITLE
Enhancement: Show approximate % completion

### ISSUE THREAD

**Issue by chadmccune** [ericaltendorf/plotman#394]
I think it would be useful to show the approximate % complete on the interactive screen and status outputs based on the %'s listed on this link: 

https://github.com/Chia-Network/chia-blockchain/wiki/Beginners-Guide#how-plots-are-created-and-7-steps-process

**Comment by altendky** [comment]
There is already the phase completion.  Look around, there is already a PR for adding a percentage.
