### ISSUE TITLE
Issue with changing -d (dst) in config.yaml -- old dst keep getting reused despite restart (root cause ID'd)

### ISSUE THREAD

**Issue by toastygunn** [ericaltendorf/plotman#43]
- I started plotting with two destinations (CHIA1 and CHIA2).
- As CHIA1 was filling up, I decided to edit config.yaml to add CHIA3 and remove CHIA1. closed plotman interactive and restarted it.
- Plotman interactive UI correctly only shows the DST specified in config.yaml (CHIA2 and CHIA3). plotman also correctly shows some //plots continuing on CHIA1.
- PROBLEM: NEW //plots are still being kicked off on CHIA1 despite it not showing up on the list.

**alfonsopereze on keybase found the root cause:**
It seems that if you have running jobs with the dest dirs that are not part of the config file, they can still be picked up here and added to the dst list. IMO, this is NOT good.
https://github.com/ericaltendorf/plotman/blob/c1665b2aa599c994931178f8e20799cfa6d4cb05/manager.py#L37

**Potential Fix**
He suggests adding a filter by the current list of dest dirs as per the config file.

My problem is that while I can write python enough to write a script that filters a logfile, i don't know how to fix this issue in this code yet.

My current workaround is that after editing config.yaml to reflect my new dst folders, I create a symlink from CHIA1 to the new destination CHIA3. That's kind of breaks plotmans ability to balance the load between destinations and is a total hack but works for now.
Thanks in advance.
-g

**Comment by ericaltendorf** [comment]
Hi, sorry this apparently wasn't adequately advertised, I believe I fixed this issue on the development branch with this commit:
https://github.com/ericaltendorf/plotman/commit/3ecc7649f1336ea1103310e80ab2431582136eda#diff-f46130ab3fffb840303f4e05537646305467f06d1e301348a45ac1b459301f39

I thought I'd generally recommended folks try the development branch, but maybe I need to better advertise that.  Please try that out and see if it works for you.

**Comment by wbuchanan** [comment]
@ericaltendorf 
Would it make sense to poll the config file periodically to detect changes to the config file that could be incorporated while things are running (e.g., if config.yaml is changed then new plots use the updated config information and old jobs continue with the state they were started with)?

**Comment by BasilHorowt** [comment]
It looks like the linked commit is now in `main`, so this issue can probably be closed?  

As for 

> "Would it make sense to poll the config file periodically to detect changes to the config file" 

This exists an issue of its own here:https://github.com/ericaltendorf/plotman/issues/254 so @wbuchanan you could subscribe to that.
