### ISSUE TITLE
dst_overrides like tmp_overrides

### ISSUE THREAD

**Issue by chadmccune** [ericaltendorf/plotman#434]
Need the same functionality as tmp_overrides for dst drives.

Alternatively, if plotman can look at current processes and calculate if the dst drive has enough drive space before scheduling a plot.

**Comment by chadmccune** [comment]
I think I need this as a result of #409

**Comment by altendky** [comment]
Yes, we are not going to add features like this to dst at this point.  It is a buffer, not a final resting place for plots.  We are trying to improve archiving configuration and flexibility.

https://github.com/ericaltendorf/plotman/issues/409#issuecomment-840823104
