### ISSUE TITLE
Plotman spent 1+ hour on copying files from tmp to dst

### ISSUE THREAD

**Issue by yijiasu** [ericaltendorf/plotman#459]
So I am using an external HDD as the `dst` and skipped the `archive`. At the end of Phase 4, I found multiple tasks(more than 4) are copying files from `tmp` to `dst` simultaneously. Which reduced the writing speed significantly.

I would like this copying to be done 1-by-1. E.g. if there's a tasking writing to `dst`, other completed tasks will wait and start until the HDD is released.

Is this possible to do? Or am I missing anything here? Thanks

**Comment by chadmccune** [comment]
I'm pretty sure plotman doesn't control that....that's the chia plotter

**Comment by yijiasu** [comment]
> I'm pretty sure plotman doesn't control that....that's the chia plotter

do you have any ideas about how to control this? or you use some SSD as `dst`?

**Comment by chadmccune** [comment]
I personally use ssd's for dst and then archive over the network

**Comment by altendky** [comment]
At this point, I set dst == tmp and archive from there.  Lots of options depending on your goals and hardware.
