### ISSUE TITLE
Include plot_id in log filenames

### ISSUE THREAD

**Issue by cryptk** [ericaltendorf/plotman#500]
**Describe the request**
Currently finding the log file for a running plot is a bit clumsy.  You either need to grep through the log files directory for the plot id to find the relevant log file to open it, or you need to run `plotman details` with the plotid to get the returned log file.  The output from `plotman details` isn't in any kind of standard machine parsable format, so going through that involves some further grep/sed/awk to get the log filename out of it.

I would propose including the plot id that the chia processes are referenced by everywhere else in the filename.  Perhaps the filenames could end up something like this:

`5d1ff2bf-2021-05-16T06_35_43.796517-05_00.log`

This would allow easily locating of the log files for review.

**Comment by altendky** [comment]
Would be nice...  if the plot id weren't created after the file.  `:]`  Though we have talked about renaming the file once the id has been written to it.  I haven't checked if that's a thing we'll be able to do in Windows though, when we grow Windows support.

And yes, generally adding computer parseable output would be nice, though not something I expect to get done generally in the near future.  Out of curiosity, what is your use case for parsing the output?

**Comment by cryptk** [comment]
Parsing the output allows me to create a script that I can give a plot id to and it returns the filepath of the log file.  This lets me easily open up the log file that I want and automate some of the clumsiness mentioned above.

**Comment by cryptk** [comment]
All of this originally happened because when I set up plotman, it wasn't obvious from the documentation that running via `plotman interactive` is the "preferred" way to run it.  I wanted it to generate plots, so I ran `plotman plot`, which did dutifully generate plots... up until my dst folder got full and all kinds of lovely things happened involving losing several hours worth the plotting.  After poking through the logs to figure out what went on (which is where I identified the issue above) I figured out that you can either run `plotman plot` AND `plotman archive` separately, or you can run `plotman interactive` and have it run both for you.  That's a separate documentation issue though.

For the log issue, have you considered creating symlinks with the "final" log name (with the plot id) that point to the appropriate log files, and then after the plotting is complete, remove the symlink and rename the log file to the "final" name?  While they aren't super commonly used, Windows does support symbolic links.

**Comment by altendky** [comment]
Also, you want to use archiving for distribution of plots to their final resting places.  `dst` is not meant as that despite the misleading name.  We are trying to make various improvements around this.  Likewise around how to run plotman.

Last I checked, junctions on Windows required admin approval?

**Comment by cryptk** [comment]
Yes, I had the archiving configured properly to rsync over to the target system, that wasn't the issue.  It was that it wasn't clear from the docs if I wanted to run `plot`, `archive` or `interactive` (the answer is to either run `interactive` OR run both `plot` AND `archive`).

Doing some reading online, it looks like you can run mklink without admin permissions in the more recent versions of Windows 10 as long as you enable an extra option:

```
On Windows 10’s Creators Update, you can use a normal Command Prompt window, without running it as an Administrator. However, to do this without an Administrator Command Prompt window, you must first enable Developer Mode from Settings > Update & Security > For Developers.
```

The above I found from https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by altendky** [comment]
Yeah, maybe.  I expect that in most cases this doesn't matter and when it does it can be solved by a grep or a new plotman subcommand that reports the file/plot id mapping, or a static file we update when we find the plot id for a given file.

Regardless, sorry for the trouble getting started.  Improving the separation to allow both 'manual' running and running 'as a service' cleanly and 'obviously' is in my short list of big picture goals.

**Comment by cryptk** [comment]
We can probably just close this then.  One thing that might be nice is adding an optional "-json" parameter or something to some of the commands (the ones it makes sense for) such as the `status`, `details`, `files` commands.  That would make discovery of the log files easier as well.  In the meantime, I'll go ahead and close this issue.
