### ISSUE TITLE
help installing

### ISSUE THREAD

**Issue by ukdomainers** [ericaltendorf/plotman#531]
hi am running centos 8 stream
ive installed plotman but when i go to
plotman config generate

```python-traceback
Traceback (most recent call last):
  File "/home/ukdomain/chia-blockchain/venv/bin/plotman", line 5, in
    from plotman.plotman import main
  File "/home/ukdomain/chia-blockchain/venv/lib/python3.7/site-packages/plotman/plotman.py", line 10, in
    from plotman import analyzer, archive, configuration, interactive, manager, plot_util, reporting
  File "/home/ukdomain/chia-blockchain/venv/lib/python3.7/site-packages/plotman/interactive.py", line 1, in
    import curses
  File "/usr/local/lib/python3.7/curses/init.py", line 13, in
    from _curses import *
ModuleNotFoundError: No module named '_curses'
(venv) [ukdomain@server chia-blockchain-gui]$
```

tried for hours looking over the web
any help would be appriceated

**Comment by ArminAghayan** [comment]
Im pretty sure this is a syntax issue in your config

**Comment by IvanWongw** [comment]
Python failed to copy the so file of _curses under linux to the specified directory during make install. The system is missing the so package of _curses, so _curses cannot be imported.

Check under /usr/local/lib/python3.7/lib-dynload/ to see if there is a so file for _curses.

**Comment by ukdomainers** [comment]
thanks for your reply no cant find any file _curses

**Comment by IvanWongw** [comment]
> 谢谢您的回复找不到任何文件_curses

Install ncurses on the system, then reinstall python.

      #Ubuntu:
        sudo apt-get install libncurses5 libncurses5-dev libncursesw5

      #centos:
        yum -y install ncurses-libs ncurses-devel

      #Recompile and install python
    
        sudo wget https://www.python.org/ftp/python/3.7.7/Python-3.7.7.tgz
    
        sudo tar -zxvf Python-3.7.7.tgz ; cd Python-3.7.7
    
        ./configure --enable-optimizations; sudo make -j$(nproc) altinstall


Then you can use plotman normally

**Comment by ukdomainers** [comment]
thats done the job 
thanks

**Comment by altendky** [comment]
@IvanWongw, thanks for helping out and getting this resolved.
