### ISSUE TITLE
[Proposal] Add a command to test the config

### ISSUE THREAD

**Issue by rafaelsteil** [ericaltendorf/plotman#559]
From Keybase: 

> We should add a plotman config test command to check all drives are writable, chia can be found, etc.
> Should be able to write tmp files each place, run chia version or such, ssh for archive dirs, etc.

**Comment by climbingblake** [comment]
that would be a great addition. My plotman just stopped writing to one of my nvme ssds and its trying to double up on the other one, obv causing a backup.
