### ISSUE TITLE
Add support for farmer/pool public key (-p -f respectively)

### ISSUE THREAD

**Issue by mekarawr** [ericaltendorf/plotman#611]
I'm using plotman on another computer so I would need it to launch the chia plotting and pass both -p and -f

**Comment by josephbolus** [comment]
You can already do this by editing the last two lines on the plotman.yaml config file.

plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 4         # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 4608     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        **farmer_pk: <FARMER_KEY_HERE
        pool_pk: >POOL_KEY_HERE>**

**Comment by mekarawr** [comment]
> You can already do this by editing the last two lines on the plotman.yaml config file.
> 
> plotting:
> k: 32
> e: False # Use -e plotting option
> n_threads: 4 # Threads per job
> n_buckets: 128 # Number of buckets to split data into
> job_buffer: 4608 # Per job memory
> # If specified, pass through to the -f and -p options. See CLI reference.
> **farmer_pk: <FARMER_KEY_HERE pool_pk: >POOL_KEY_HERE>**

coll gonna try that, but at anything these options should be in the yaml file created with configure and with the explanation for the directive
