### ISSUE TITLE
 ssh: connect to host myfarmer port 22: Connection timed out

### ISSUE THREAD

**Issue by babbahotep** [ericaltendorf/plotman#629]
Hi recently getting  
```
ssh: connect to host myfarmer port 22: Connection timed out
or connect to host myfarmer port 22: Connection refused
```
What's that mean? Where is plotman trying to connect to?

**Comment by mruckli** [comment]
I would assume this to be related to the default archiving config. Either change the config to set it up for your system or disable it with the information here: https://github.com/ericaltendorf/plotman/wiki/Archiving#disable-archiving-in-plotman

**Comment by babbahotep** [comment]
ahh, ty!
