### ISSUE TITLE
Too many plotters per temp drive

### ISSUE THREAD

**Issue by jcapogna** [ericaltendorf/plotman#63]
I am occasionally seeing the limit for how many plotters per temp drive being ignored. 

My suspicion is that the phases like 2:? and 4:? are to blame. 

My config only allows 1 plotter per temp drive. In the screenshot below, notice how drive "temp7" show as OK even though there is a job present. This happened while in phase 2:?. Once it moved on to phase 2:1, it was no longer showing as ready. 

![Screenshot from 2021-03-31 21-12-04](https://user-images.githubusercontent.com/9100404/113234243-84f68500-9266-11eb-9820-30c53bdf8f7d.png)

**Comment by jcapogna** [comment]
This actually just happened again twice in a few minutes. I had plotters in phase 2:? and 4:? and it created two new plotters despite being at the limit.

**Comment by ericaltendorf** [comment]
Let me know if this is fixed (or just close the issue if it is). Thanks!

**Comment by jcapogna** [comment]
I haven't had this issue since pulling down these changes. I'm pretty sure it's fixed. Will reopen if needed.
