### ISSUE TITLE
Archive free space check grep pattern problem

### ISSUE THREAD

**Issue by digi24** [ericaltendorf/plotman#647]
Hello,
I had a problem, that the archive function was just sleeping, but not rsyncing.  I identified a slash in the grep pattern that is causing the problem for me, but maybe other systems return a trailing slash on their `df`output.

https://github.com/ericaltendorf/plotman/blob/1876d4cbda73fb38584f95113a00f01af1e21704/src/plotman/archive.py#L89

Changing the line linked above to 
```df_cmd = ('ssh %s@%s df -aBK | grep " %s"' %```
solves it for me.  

Is the slash system dependent, or am I doing something wrong?

**Comment by randellhodges** [comment]
I think that grep pattern was to make sure you don't get partial matches, or false matches.

Say you have mounts like:

/mnt/plots/plot
/mnt/plots/plot1

Without the trailing slash, `grep " /mnt/plots/plot"` is going to return data for both. If the trailing slash is left in, that would ensure it literally matches `/mnt/plots/plot` and not include `/mnt/plots/plot1` in the results.

All my mounts are like:

/mnt/chia/plots/00
/mnt/chia/plots/01
/mnt/chia/plots/02

And everything works well.

What is your system and what is the results of just `df -aBK`?

**Comment by digi24** [comment]
@randellhodges Thank you very much.  I was not using the indexes at all and having the filesystem handle the distribution. So, it is my mistake, and a slight bug, that I could use it in a wrong way.
