### ISSUE TITLE
plotman hangs when dest folder is on nfs drive

### ISSUE THREAD

**Issue by kastermight** [ericaltendorf/plotman#714]
Title pretty much says it all. I'm on Ubuntu 20.04. When dest folder is on local drive everything is fine. When I change dest to be on nfs drive plotman just hangs. It does run first plotting job and that's it. Screen is empty. I can't kill it afterwards. Not even with kill -9. 

Thanks.

**Comment by ebeng** [comment]
You must be doing something wrong. 
Share some what more about your setup and nfs setup. 
Im running also a few servers with a NFS server where all the plots are being sent to. 
Check if your harvester can write on the NFS directory (/mnt/xxx)

**Comment by kastermight** [comment]
Happy to share if you tell me what exactly. NFS directories are readable/writable manually. Not sure what do you mean by harvester permissions. I'm not running a harvester not full node on that machine. Just the plotter which then writes to nfs. As a side note, different plot manager has absolutely no issues working with the exactly the same setup. I do  want to get to the bottom of this, but meanwhile I'm not using plotman due to this issue.

**Comment by jayhohoho2019** [comment]
Sorry I can't help here but could you list the other plot managers you've tried?  I'm trying plotman, plotting to local drives, with archive mode turned off.  It seems to work except it keeps plotting when dst drives are nearly full, which gets very annoying.  I'm not sure what I'm missing here or why plotman wouldn't make dst free space as a criterion in determining whether to start a new plot to a dst drive.

**Comment by jayhohoho2019** [comment]
Btw, I'm not using archive mode but I thought archiving in plotman was supposed to rsync from local dst drives to remote file servers, but asynchronously outside of the chia plot create processes.  If you make an nfs share a dst drive in chia plot create, what performance are you getting compared to local writes?

**Comment by kastermight** [comment]
> Sorry I can't help here but could you list the other plot managers you've tried? I'm trying plotman, plotting to local drives, with archive mode turned off. It seems to work except it keeps plotting when dst drives are nearly full, which gets very annoying. I'm not sure what I'm missing here or why plotman wouldn't make dst free space as a criterion in determining whether to start a new plot to a dst drive.

I thinks it's a known limitation. I saw a PR to tackle this but it hasn't been merged as far as I can tell.

**Comment by kastermight** [comment]
> Btw, I'm not using archive mode but I thought archiving in plotman was supposed to rsync from local dst drives to remote file servers, but asynchronously outside of the chia plot create processes. If you make an nfs share a dst drive in chia plot create, what performance are you getting compared to local writes?

It's not great. But I had to go this route because my local hard drive turned out to be faulty and slow. But I'm in the process of installing 10Gbps NICs on both plotter and farmer machines so it's not a bottleneck anymore.

**Comment by ebeng** [comment]
> > Btw, I'm not using archive mode but I thought archiving in plotman was supposed to rsync from local dst drives to remote file servers, but asynchronously outside of the chia plot create processes. If you make an nfs share a dst drive in chia plot create, what performance are you getting compared to local writes?
> 
> It's not great. But I had to go this route because my local hard drive turned out to be faulty and slow. But I'm in the process of installing 10Gbps NICs on both plotter and farmer machines so it's not a bottleneck anymore.

same here :)

**Comment by altendky** [comment]
`dst` is not meant to be the final location of plots.  Archiving handles that.  See the wiki for setup instructions.  Hopefully soon we will release a version with the reworked archival configuration that doesn't require use of rsyncd for local paths.

**Comment by kastermight** [comment]
> `dst` is not meant to be the final location of plots. Archiving handles that. See the wiki for setup instructions. Hopefully soon we will release a version with the reworked archival configuration that doesn't require use of rsyncd for local paths.

sure i get the logistics of it, best practices etc. but it should work with nfs as a dst right? for the system nfs shouldn't be any different than a local path, and another plot manager i'm using atm works just fine. so i was wondering what kind of extra checks plotman is doing that gets it stalled/frozen/hung.

**Comment by altendky** [comment]
In my limited experience, much of it many years ago, NFS is notorious for hard hanging programs anytime anything isn't quite right.  So yeah, it should work but I'm not super surprised that NFS is doing something like this.  Any chance you can run a Python debugger and step through to figure out what particular line of code is hanging?  Or maybe we can get somewhere with `python -m trace --trace venv/bin/plotman plot &> the_trace` (and share the `the_trace` file).  Even though this does seem like a bug to at least some degree, it doesn't seem like an optimal use of time improving plotman.  Using network drives as a local buffer for times when archiving is having trouble doesn't seem like a common need.  The reworked archiving is available on the development branch and updated instructions are linked from the wiki.

**Comment by kastermight** [comment]
Hi @altendky thanks for spending time replying. My python debugging skills are limited to some print messages and anything above that feels daunting and regrettably I don't feel comfortable sniffing through bunch of codes. And even if I managed to find enough will power to do so, the usage of ncurses seems to make things worse for me. In any case, I don't think my NFS directories "isn't quite right", as I said I don't have problem accessing it manually, and another plot manager works with pretty much out of the box, which I most likely will stick to.

The reason I'm not using my nsf drives in archival is I don't have local dst drives. And even if I did, I could only add 1 drive, which wouldn't be ideal for the number of parallel plots I'm doing. 

I totally agree about prioritizing development and if the issue I was having is not too common it's completely fine to disregard it until it becomes more so. 


I'll close this issue. Thank again. Cheers.

**Comment by altendky** [comment]
I think there are a few misunderstandings here.  I did not mean you had set up your NFS mounts wrong, just that NFS fails hard anytime it gets unhappy instead of timing out or returning a failure code.  As to your setup, I don't see any reason plotman can't accommodate it.  I don't have any dst drives either.  If you want to get it working, I'm happy to help.  If not, I'm glad you have something working for you.
