### ISSUE TITLE
Incorrect RAM usage output

### ISSUE THREAD

**Issue by GTANAdam** [ericaltendorf/plotman#727]
It seems that the output used memory is showing both the shared and private memory which isn't actual RAM usage. In order to fix this, the tool has to query the [_Proportional set size_](https://en.wikipedia.org/wiki/Proportional_set_size) of the process.

**Comment by altendky** [comment]
Does https://github.com/ericaltendorf/plotman/issues/228 cover this?

**Comment by GTANAdam** [comment]
> Does #228 cover this?

Yes, it seems so.
Can be marked duplicate and closed.

**Comment by altendky** [comment]
Thanks for looking.  I do need to get back to that one.  If there are any more details you think are needed there, please do add a comment.
