### ISSUE TITLE
support chia-plotter (madmax)

### ISSUE THREAD

**Issue by nqzhang** [ericaltendorf/plotman#762]
**Describe the request**
I tested a plot software that is faster than the official team。Can we support it

https://github.com/madMAx43v3r/chia-plotter

**Images**

**Additional comments**

**Comment by yl** [comment]
+1

**Comment by maxbelz** [comment]
+1

**Comment by F1DNA** [comment]
While I am sure there are scenarios where it is not fast, I have test this with a server and enough ram for a RAM disk, a system with a 3rd gen i5 (4 cores) and a single sata SSD and am currently testing it on a system with spinning disks in RAID 0.  It is FASTER.  If you have a "balanced" system, perhaps you need to "rebalance" to take advantage of this new plotter.

**Comment by altendky** [comment]
There seems a good chance.  I'm personally waiting to hear more details.  It seems promising, but my understanding is that it isn't creating exactly the same thing as the official plotter.

Is it CLI compatible with the official plotter?  What needs to be different?  Does it really need to be different or could they make themselves compatible?

**Comment by jinthagerman** [comment]
Sounds like it might be integrated into the official cli

https://github.com/Chia-Network/chia-blockchain/discussions/452#discussioncomment-854926

**Comment by ebeng** [comment]
+1

**Comment by yodiaditya** [comment]
+1

**Comment by altendky** [comment]
This has already been implemented, PRed, and merged to `development`.  It will be in the next release.
