### ISSUE TITLE
Cannot run Plotman Plot (I'm sure its something I'm doing wrong)

### ISSUE THREAD

**Issue by tpatten123** [ericaltendorf/plotman#765]
When I run plotman plot I get the following error:

```python-traceback
tpatten@Dell-PE140:~/chia-blockchain$ plotman plot
...starting plot loop
Traceback (most recent call last):
  File "/home/tpatten/.local/bin/plotman", line 8, in <module>
    sys.exit(main())
  File "/home/tpatten/.local/lib/python3.8/site-packages/plotman/plotman.py", line 145, in main
    wait_reason = manager.maybe_start_new_plot(cfg.directories, cfg.scheduling, cfg.plotting)
  File "/home/tpatten/.local/lib/python3.8/site-packages/plotman/manager.py", line 163, in maybe_start_new_plot
    p = subprocess.Popen(plot_args,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chia'
```

My config file makes no mention of a chia directory so I'm a little lost. Any ideas?

**Comment by toboladao** [comment]
please, post the plotman.yaml.

**Comment by tpatten123** [comment]
Thanks, here it is:


# Default/example plotman.yaml configuration file

# Options for display and rendering
user_interface:
        # Call out to the `stty` program to determine terminal size, instead of
        # relying on what is reported by the curses library.   In some cases,
        # the curses library fails to update on SIGWINCH signals.  If the
        # `plotman interactive` curses interface does not properly adjust when
        # you resize the terminal window, you can try setting this to True. 
        use_stty_size: True

# Where to plot and log.
directories:
        # One directory in which to store all plot job logs (the STDOUT/
        # STDERR of all plot jobs).  In order to monitor progress, plotman
        # reads these logs on a regular basis, so using a fast drive is
        # recommended.
        log: /home/tpatten/chia-blockchain/logs

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        tmp:
                - /media/tpatten/SSD1
                - /media/tpatten/SSD2
                - /media/tpatten/SSD3
                

        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        tmp_overrides:
                # In this example, /mnt/tmp/00 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                "/mnt/tmp/00":
                        tmpdir_max_jobs: 3

        # Optional: tmp2 directory.  If specified, will be passed to
        # chia plots create as -2.  Only one tmp2 directory is supported.
        # tmp2: /mnt/tmp/a

        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        dst:
                - /media/tpatten/HDD1
                - /media/tpatten/HDD2
                - /media/tpatten/HDD3
                - /media/tpatten/HDD4

        # Archival configuration.  Optional; if you do not wish to run the
        # archiving operation, comment this section out.
        #
        # Currently archival depends on an rsync daemon running on the remote
        # host.
        # The archival also uses ssh to connect to the remote host and check
        # for available directories. Set up ssh keys on the remote host to
        # allow public key login from rsyncd_user.
        # Complete example: https://github.com/ericaltendorf/plotman/wiki/Archiving
        archive:
                rsyncd_module: plots # Define this in remote rsyncd.conf.
                rsyncd_path: /plots # This is used via ssh. Should match path
                                    # defined in the module referenced above.
                rsyncd_bwlimit: 80000  # Bandwidth limit in KB/s
                rsyncd_host: myfarmer
                rsyncd_user: tpatten
                # Optional index.  If omitted or set to 0, plotman will archive
                # to the first archive dir with free space.  If specified,
                # plotman will skip forward up to 'index' drives (if they exist).
                # This can be useful to reduce io contention on a drive on the
                # archive host if you have multiple plotters (simultaneous io
                # can still happen at the time a drive fills up.)  E.g., if you
                # have four plotters, you could set this to 0, 1, 2, and 3, on
                # the 4 machines, or 0, 1, 0, 1.
                #   index: 0


# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before [tmpdir_stagger_phase_major : tmpdir_stagger_phase_minor]
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major : phase minor].
        # e.g, with default settings, a new plot will start only when your plot
        # reaches phase [2 : 1] on your temp drive. This setting takes precidence
        # over global_stagger_m
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        tmpdir_max_jobs: 3

        # Don't run more than this many jobs at a time in total.
        global_max_jobs: 8

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 20

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 1200


# Plotting parameters.  These are pass-through parameters to chia plots create.
# See documentation at
# https://github.com/Chia-Network/chia-blockchain/wiki/CLI-Commands-Reference#create
plotting:
        k: 32
        e: False             # Use -e plotting option
        n_threads: 72       # Threads per job
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 3389     # Per job memory
        # If specified, pass through to the -f and -p options.  See CLI reference.
        #   farmer_pk: ...
        #   pool_pk: ...

**Comment by toboladao** [comment]
If you are using the same machine to plot and store them, I would consider disabling the archive and leaving only dst configured.

**Comment by toboladao** [comment]
tmp_overrides:
            # In this example, /mnt/tmp/00 is larger than the other tmp
            # dirs and it can hold more plots than the default.
            "/mnt/tpattern/SSD1":
                    tmpdir_max_jobs: 3
"/mnt/tpattern/SSD2":
                    tmpdir_max_jobs: 3
"/mnt/tpattern/SSD3":
                    tmpdir_max_jobs: 3

**Comment by toboladao** [comment]
I faced similar problems, and I only managed to solve it by testing and getting it wrong several times.

**Comment by tpatten123** [comment]
Thanks, I tried changing what you recommended and it listed all of my plots and had the same issue at the end. Any other ideas by chance?

**Comment by toboladao** [comment]
> Thanks, I tried changing what you recommended and it listed all of my plots and had the same issue at the end. Any other ideas by chance?

Will I be assigned read and write permissions for the dirs? sudo chown -R user:group /path/your/dirs
And are you running plotman with venv enabled?
/path/to/chia-blockchain/. ./activate

**Comment by toboladao** [comment]
n_threads: 72???

**Comment by tpatten123** [comment]
I guess I'm not sure what venv is? 
I believe I am the owner of my ow directories.
I had already activated the chia blockhain but maybe I'm doing it wrong.

I have 2 devices, one with a xeon E2236, one with dual Xeon 5218 gold
I found on another forum that using just a couple threads leaves like 50% of your threads unused, if you use all and go over then the OS will use virtual cores and you'll utilize 100%. Now I'm not sure how accurate it is but I checked and I was only using 50% and now using 100%

**Comment by toboladao** [comment]
You need to go to the directory where your chia-blockchain is and type . ./activate. Once this is done, you activate venv. About CPU, it seems to me that you need to set the number of threads and colors to work on each plot. I use a Xeon-E 2288G - 8 c / 16 t and set n=2.

**Comment by tpatten123** [comment]
I did the . ./Activate part prior to this, I guess I'm a bit lost. I tried generating a new config.yaml changing what needed to be changed and I got the same issue.

**Comment by altendky** [comment]
Since I saw a comment about disabling archiving, please consider reading the new explanation of archiving [in the wiki](https://github.com/ericaltendorf/plotman/wiki/Archiving).  While you could use archiving locally before and it worked well, the latest release, v0.4, makes it much simpler to setup.

**Comment by Elbers60** [comment]
Gotta love no actual help with this janky useless plot manager. I suggest you move on

**Comment by altendky** [comment]
@Elbers60 was there something you needed help with?  If so it is best to [start a discussion](https://github.com/ericaltendorf/plotman/discussions/new) or check in on the #plotman channel on chia's keybase.  But sure, sometimes we fail to keep up with everyone that needs help.

As to this issue, I'm not really sure what is wrong at this point.  Interactive help on keybase may be the best bet.

**Comment by Elbers60** [comment]
> @Elbers60 was there something you needed help with?  If so it is best to [start a discussion](https://github.com/ericaltendorf/plotman/discussions/new) or check in on the #plotman channel on chia's keybase.  But sure, sometimes we fail to keep up with everyone that needs help.
> 
> As to this issue, I'm not really sure what is wrong at this point.  Interactive help on keybase may be the best bet.

I actually figured it out. Sorry, for the vile comments. This guy needs to update his config.yaml when I updated to 1.1.17 and had to reinstall plotman. The file is slightly different with the archiving updates. I tried to use the same file and couldn't get it to reopen. New file plugged in my directories and it's working again.

**Comment by altendky** [comment]
Glad you got it working.  We all have our frustrated moments.  `:]`

**Comment by tpatten123** [comment]
Thanks @Elbers60 , I tried to reinstall plotman and create a new config and still have the same issue. Does my chia installation need to be in a certain directory? I'm plotting on Ubuntu 20.04 and had to install chia manually, would not be surprised if I did something incorrectly. It seems to me that plotman cannot find my chia directory where all the other commands live, I'm just not sure how to point it to the right place.

**Comment by Elbers60** [comment]
> Thanks @Elbers60 , I tried to reinstall plotman and create a new config and still have the same issue. Does my chia installation need to be in a certain directory? I'm plotting on Ubuntu 20.04 and had to install chia manually, would not be surprised if I did something incorrectly. It seems to me that plotman cannot find my chia directory where all the other commands live, I'm just not sure how to point it to the right place.

When did you last make a new config file? I did last night and it looked slightly different from how it has.

**Comment by altendky** [comment]
@tpatten123, are you still getting the originally reported `No such file or directory: 'chia'` error?  That means that you do not have the chia environment activated, presuming you installed that way. If you used `git clone` to get chia then you will need to activate the env such as by `source ./activate` as they recommend at the end of running the install script.  Note that this is specific to that particular shell session.  Activating in one window and running plotman in another won't work.

Have you had a chance to join keybase?

**Comment by tpatten123** [comment]
That was basically what I was doing wrong. I had activated but was trying to run plotman in a separate instance of terminal which hadn't been activated! thank you!
