### ISSUE TITLE
discover remote rsyncd targets that are mounted more than once

### ISSUE THREAD

**Issue by mharsch** [ericaltendorf/plotman#773]
**Describe the bug**

With the change to 0.4, the plotman client no longer discovers eligible targets if they are mounted at multiple mountpoints (e.g. to work around the limitation where the site_root must only contain plot targets).

**To Reproduce**
For example, the same drive could be mounted under /mnt/disk0 and also under /plots/disk0 and site_root set to /plots but the df command run over ssh to discover rsync destinations doesn't find any paths starting with /plots because the output only includes the first mountpoint (/mnt/disk0).

This can be fixed by adding the '-a' option to the 'df' command in the rsyncd target description.

**Comment by altendky** [comment]
Makes sense, thanks for the explanation.  I'll change that.  If you haven't already addressed this for yourself, you could duplicate the default target definition into your own plotman config, tweak it there, and use that.

**Comment by altendky** [comment]
released in v0.4.1

https://github.com/ericaltendorf/plotman/blob/v0.4.1/CHANGELOG.md

**Comment by altendky** [comment]
@mharsch, was this resolved for you in v0.4.1?

**Comment by mharsch** [comment]
Yes, fixed in 0.4.1
Thanks.
