### ISSUE TITLE
Madmax plotter

### ISSUE THREAD

**Issue by jinthagerman** [ericaltendorf/plotman#776]
Any chance support will be added for the new madmax plotter?

https://github.com/madMAx43v3r/chia-plotter

**Comment by toboladao** [comment]
This plotter is really good. I was using it to plot and plotman to file.

**Comment by altendky** [comment]
Looks like a duplicate of https://github.com/ericaltendorf/plotman/issues/762.

**Comment by jinthagerman** [comment]
Didn’t find anything when I searched. Closing
