### ISSUE TITLE
Plotman creating mnt folder in Chia-Blockchain folder and plotting to it instead of non-OS temp directories

### ISSUE THREAD

**Issue by DendyDarzartar** [ericaltendorf/plotman#809]
Hello, 

When I run the plotman plot command a /mnt/ folder is created within the chia-blockchain folder on my OS drive and the drive begins to plot to it despite that drive not being listed as a temp directory within the config file. I had to give my user folder access in order to be able to delete the folder. 

Does anyone know what could have caused this? I am wondering if I mistakenly partitioned and mounted the drives within a chia terminal window?

Everything looks correct when I check the /etc/fstab directory and the plotman's config.yaml yet attempting to plot will utilize one of the existing mount directories in name only but will plot it to the OS drive regardless of the fact that the temp directories appear to only point to the mnt folder and not to the chia-blochain directory

**Comment by altendky** [comment]
Out of curiosity, did you delete the issue template?  Or maybe you used another means to create this ticket that doesn't show you the issue template?

To debug this we'll need to see more information.  Let's start at least with what is requested in [the issue template](https://github.com/ericaltendorf/plotman/issues/new?assignees=&labels=bug&template=bug_report.md&title=).

**Comment by DendyDarzartar** [comment]
I just clicked on the new issue button along the right. 
I will fill out the template now, thank you!
