### ISSUE TITLE
log file stops at [P4] Writing C2 table . madmax

### ISSUE THREAD

**Issue by maxbelz** [ericaltendorf/plotman#897]
i have 8 simillar servers with identical setups and software.
somewhy on 1 of them plotman logs stops at [P4] Writing C2 table . looks like plots are still finish good, so issue just in logs:

```
Phase 3 took 1584.15 sec, wrote 21871177154 entries to final plot
[P4] Starting to write C1 and C3 tables
[P4] Finished writing C1 and C3 tables
[P4] Writing C2 table
```

expected behavior - 3 more lines like this : 
```
[P4] Finished writing C2 table
Phase 4 took 401.263 sec, final plot size is 108836070683 bytes
Total plot creation time was.....
```

**Comment by altendky** [comment]
It looks like you deleted the entire template guiding how to file a report.

The short answer is, as soon as the plotting process has been launched it is out of plotman's hands.  Debug the plotter I guess.  You can check `ps aux | grep chia_plot` while a plot is running to see the command line and then run that yourself to test it without plotman being involved at all.

**Comment by maxbelz** [comment]
> It looks like you deleted the entire template guiding how to file a report.
> 
> The short answer is, as soon as the plotting process has been launched it is out of plotman's hands. Debug the plotter I guess. You can check `ps aux | grep chia_plot` while a plot is running to see the command line and then run that yourself to test it without plotman being involved at all.

ok , thanks, than its madmax issue.
