### ISSUE TITLE
ParserError first time running plotman

### ISSUE THREAD

**Issue by hutchwilco** [ericaltendorf/plotman#933]
### Discussed in https://github.com/ericaltendorf/plotman/discussions/932

<div type='discussions-op-text'>

<sup>Originally posted by **hutchwilco** September 30, 2021</sup>
I've got the following error when running `plotman interactive`
I've checked the yaml, several online yaml validators confirm my check.
The only thing is I'm running on a machine that had chia installed via the experimental .deb file rather than "git install" that I'm used to. So I've not activated an environment when running this. Plotman is installed in /home/<user>/.local/bin/

Any help would be appreciated. plotman v 0.5.3

>
>     raise ParserError("while parsing a block mapping", self.marks[-1],
> yaml.parser.ParserError: while parsing a block mapping
>   in "<unicode string>", line 44, column 9:
>             tmp: /mnt/ram
>             ^
> expected <block end>, but found '<block mapping start>'
>   in "<unicode string>", line 51, column 10:
>              tmp2: /mnt/nvme1
>              ^

</div>

**Comment by altendky** [comment]
This doesn't seem to be a bug, at least not yet, so we can just discuss it over at https://github.com/ericaltendorf/plotman/discussions/932.
