### ISSUE TITLE
`plotman archive` does not, in fact, archive.

### ISSUE THREAD

**Issue by jkbecker** [ericaltendorf/plotman#96]
Instead, it just returns a tuple with the command list that could perform an archive command.

https://github.com/ericaltendorf/plotman/blob/349d13ab315518d22d55b04ceead17b3addb4ff7/plotman.py#L135

https://github.com/ericaltendorf/plotman/blob/349d13ab315518d22d55b04ceead17b3addb4ff7/archive.py#L138

**Comment by cmeyer90** [comment]
I attempted a fix for this - see PR here: https://github.com/ericaltendorf/plotman/pull/109

Still testing but appears to work fine in 'plotman archive' mode.

**Comment by chadmccune** [comment]
I'm experiencing this problem in 0.3.1...

in 'plotman interactive', it archives, but in 'plotman archive', it just loops never executing rsync as far as I can tell

**Comment by altendky** [comment]
@chadmccune, that is a separate issue.  Please provide example outputs etc in a new ticket.
