### ISSUE TITLE
archiving does not pick up compressed plots

### ISSUE THREAD

**Issue by jayhohoho2019** [ericaltendorf/plotman#969]
**Describe the bug**

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Set up config with '...'
2. Run other programs '....'
3. Run Plotman with '....'

**Expected behavior**

**System setup:**
 - OS: Ubuntu Server 
 - Method of archiving: rsync

**Config**
<details> <summary>full configuration</summary>

```yaml
# paste your complete configuration file contents here.
```

</details>

**Additional context & screenshots**

**Comment by altendky** [comment]
Sorry to leave you hanging here.  I'm not going to promise anything, but there is some discussion about putting some work into plotman again.  It is becoming of personal interest, so there's some hope it actually happens.

Thanks for the report.  Properly handling compressed plots would certainly be a key functionality to add/fix.

**Comment by jayhohoho2019** [comment]
No worries.  Been using plow.py but it's not as hands free as plotman archive (used to be).  Other than handling compressed plot sizes, since some of us are doing replotting, some functionality to free up the right amount of space on the archive drive might be helpful too.  For now I wrote a separate script to do that.   Thanks.

**Comment by jayhohoho2019** [comment]
I've combined my c0 plots removal shell script with plow.py and made my own replow.py.  It's able to check available space on local and remote dest and remove a batch of c0 plots if any and continue plowing.  tested it on filling a few drives and seems good.  so I don't really need this any more.
